p2p/src/actors/dialer.rs
p2p/src/actors/listener.rs
p2p/src/config.rs
p2p/src/connection/mod.rs
p2p/src/network.rs

TCP_NODELAY is not on by default in contrary to Golang, so wanted to open a pr for it :)

[p2p] add config to allow setting TCP_NODELAY on TcpStreams 

---

Cargo.lock
examples/chat/Cargo.toml
p2p/Cargo.toml
p2p/src/actors/tracker/actor.rs
p2p/src/config.rs

* Avoid regeneration of bit vector each time a peer address is discovered
* Maintain connections with all peers in tracked sets
* Gossip bit vectors from all tracked sets
* Migrate logic from actor to new structures
* Remove unnecessary async function definitions

[p2p] Support Connections With Multiple Sets

---

examples/chat/src/handler.rs
examples/chat/src/main.rs
p2p/src/actors/router/actor.rs
p2p/src/actors/router/ingress.rs
p2p/src/channels.rs

* When providing `None` as a recipient, a message will be sent to all connected peers

[p2p] Broadcast Support

---

p2p/src/actors/tracker/actor.rs
p2p/src/connection/handshake.rs
p2p/src/crypto/ed25519.rs
p2p/src/crypto/mod.rs

* To avoid confusion (`dst` has a specific meaning in some cryptographic schemes), `dst` has been renamed to `namespace` for `Crypto` users.

[crypto] Change DST to Namespace

---

p2p/src/crypto/ed25519.rs
p2p/src/crypto/mod.rs
p2p/src/crypto/utils.rs

* Change name of provided `data` for signing to `message`
* Clarify that `message` should not be hashed prior to invocation

[p2p/crypto] Rename `data` to `message`

---

p2p/src/channels.rs

* Make it possible for a client of the SDK to spawn multiple senders over the same channel

[p2p] Add `#[derive(Clone)]` to Sender

---

Cargo.lock
examples/chat/Cargo.toml
p2p/Cargo.toml
p2p/src/actors/tracker/actor.rs

* When creating a new `PeerSet`, make sure to include ourself (otherwise, we'll request our peer record...which throws an error).

[p2p] Add self to `PeerSet`

---

Cargo.lock
examples/chat/Cargo.toml

* Release a new version of `chat` that uses #32

[examples/chat] Bump Version

---

Cargo.lock
examples/chat/Cargo.toml
p2p/Cargo.toml
p2p/src/config.rs

* Reduce the time it takes for a peer to terminate a connection

[p2p] Reduce read timeout on `Config::aggressive`

---

Cargo.lock
cryptography/Cargo.toml
cryptography/src/lib.rs
examples/chat/Cargo.toml
p2p/Cargo.toml

* Expose `utils::payload` to make it easier to write external `cryptography::Scheme` implementations.

[crypto] Expose `utils`

---

Cargo.lock
Cargo.toml
cryptography/Cargo.toml
examples/chat/Cargo.toml
p2p/Cargo.toml

* Release a new version of `p2p` to ensure `Scheme` is the same version for people that import both `crytpography` and `p2p`.

[cargo] Create Workspace Dependencies

---

Cargo.lock
cryptography/Cargo.toml
cryptography/src/bls12381/benches/dkg_recovery.rs
cryptography/src/bls12381/benches/reshare_recovery.rs
cryptography/src/bls12381/benches/signature_aggregation.rs
cryptography/src/bls12381/benches/signature_generation.rs
cryptography/src/bls12381/benches/signature_verification.rs
cryptography/src/bls12381/dkg/arbiter.rs
cryptography/src/bls12381/dkg/contributor.rs
cryptography/src/bls12381/dkg/mod.rs
cryptography/src/bls12381/dkg/ops.rs
cryptography/src/bls12381/dkg/utils.rs
cryptography/src/bls12381/mod.rs
cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/mod.rs
cryptography/src/bls12381/primitives/ops.rs
cryptography/src/bls12381/primitives/poly.rs
cryptography/src/bls12381/scheme.rs
cryptography/src/lib.rs
cryptography/src/utils.rs

* Implement DKG/Resharing Procedure (using `Arbiter` and `Contributor`) for BLS12-381
* Implement `Scheme` trait for BLS12-381
* Implement Threshold Signatures for BLS12-381
_The following crates were used as a reference when implementing this crate. If code is very similar to the reference, it is accompanied by a comment and link._
* https://github.com/celo-org/celo-threshold-bls-rs: Operations over the BLS12-381 scalar field, GJKR99, and Desmedt97.
* https://github.com/filecoin-project/blstrs + https://github.com/MystenLabs/fastcrypto: Implenting operations over the BLS12-381 scalar field with https://github.com/supranational/blst.

[cryptography] Implement BLS12-381 DKG, Resharing, Scheme, and Threshold Signatures

---

.github/workflows/crates.yml
Cargo.lock
Cargo.toml
README.md
cryptography/Cargo.toml
cryptography/src/bls12381/dkg/arbiter.rs
docs/index.html
examples/chat/Cargo.toml
examples/vrf/Cargo.toml
examples/vrf/README.md
examples/vrf/build.rs
examples/vrf/src/handlers/arbiter.rs
examples/vrf/src/handlers/contributor.rs
examples/vrf/src/handlers/mod.rs
examples/vrf/src/handlers/payloads.rs
examples/vrf/src/handlers/utils.rs
examples/vrf/src/handlers/vrf.rs
examples/vrf/src/main.rs
examples/vrf/src/wire.proto
p2p/Cargo.toml

* Introduce a new example that demonstrates how to use the cryptographic primitives introduced in #42.
* Add more context on `Arbiter` deployment options.
* Update website to list `commonware-vrf`.
* Update all crate versions.

[examples/vrf] Generate bias-resistant randomness with untrusted contributors

---

Cargo.lock
Cargo.toml
cryptography/Cargo.toml
cryptography/src/bls12381/dkg/arbiter.rs

* Explicitly refer to the "recommended option" as a superset of reliable broadcast (needed to have a timeout).

[cryptography] Improve Comments for Deployment Options

---

Cargo.lock
examples/chat/src/handler.rs
examples/chat/src/main.rs
examples/vrf/src/handlers/arbiter.rs
examples/vrf/src/handlers/contributor.rs
examples/vrf/src/handlers/vrf.rs
examples/vrf/src/main.rs
p2p/Cargo.toml
p2p/src/channels.rs
p2p/src/lib.rs
p2p/src/network.rs

* Allow a channel to specify whether or not it should be compressed (using `zstd`)
* Return an error if send fails (because the message is too large)

[p2p] Message Compression

---

Cargo.lock
runtime/Cargo.toml
runtime/README.md
runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/tokio.rs
runtime/src/utils.rs

To support integration with `p2p::authenticated`, we must return `Handle` from `Spawner::spawn`.

[runtime] Support `join`

---

p2p/src/authenticated/actors/listener.rs
p2p/src/authenticated/config.rs
p2p/src/authenticated/connection/handshake.rs
p2p/src/authenticated/connection/instance.rs
p2p/src/authenticated/connection/mod.rs
p2p/src/authenticated/network.rs

Terminate a connection prior to read/write timeout based on `handshake_timeout`.

[p2p] Restore handshake timeout functionality

---

p2p/src/authenticated/metrics.rs

Instead of declaring the `X_TYPE` at the root of the file. It declares them in the struct it is used by.

[p2p/authenticated]: modify consts scope

---

.github/workflows/coverage.yml

`cargo-tarpaulin` incorrectly attributes coverage in a number of different cases: https://github.com/xd009642/tarpaulin/issues/351

[CI] Migrate to cargo-llvm-cov

---

storage/src/archive/mod.rs
storage/src/archive/storage.rs
storage/src/journal/mod.rs
storage/src/journal/storage.rs

[storage/journal] Implement skip reads

---

runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/tokio.rs
runtime/src/utils.rs

This pull request includes several changes to improve the signaling mechanism in the `runtime` module, replacing the `Waiter` type with `Signal` and updating related methods to handle an integer value for the signal. The most important changes include modifications to the `Auditor` and `Executor` structures, updates to the `Spawner` trait, and adjustments in the `Signaler` implementation.
* [`runtime/src/deterministic.rs`](diffhunk://#diff-57b9bbe7c482353953ff44aa19e62cb28916a2b6fdbba6de0667d5084e12aee1L25-R25): Replaced `Waiter` with `Signal` in `Auditor`, `Executor`, and `Context` structures and methods, and updated the `stop` method to accept an integer value. [[1]](diffhunk://#diff-57b9bbe7c482353953ff44aa19e62cb28916a2b6fdbba6de0667d5084e12aee1L25-R25) …

[runtime] Add value (`i32`) to signal

---

cryptography/README.md
examples/chat/README.md
examples/vrf/README.md
macros/README.md
p2p/README.md
runtime/README.md
storage/README.md
utils/README.md

This pull request adds documentation badges to the README files of various components in the `commonware` project, linking to the corresponding documentation on `docs.rs`.
Documentation updates:
* [`cryptography/README.md`](diffhunk://#diff-4167d58ef14ee44a62d151f7d4da5bd99cc34a932e4a8d1193207fe653ca9c62R4): Added `Docs.rs` badge.
* [`examples/chat/README.md`](diffhunk://#diff-1deb0660a12cd239eca5630f7b7448aec0c2e4faf5d888ff4c5486289f4b6d5aR4): Added `Docs.rs` badge.
* [`examples/vrf/README.md`](diffhunk://#diff-6f540488d9822fd83112e71ae23415c55231c22654a12b1292f0834f459c7641R4): Added `Docs.rs` badge.
* [`macros/README.md`](diffhunk://#diff-73e985ca9d8395b876fe121ff3505ae9891d48caced22d8272a39668a08e168eR4): Added `Docs.rs` badge.
* …

[docs] Add link to `docs.rs`

---

Cargo.lock
Cargo.toml
storage/Cargo.toml

This pull request includes version updates for the `commonware-storage` dependency in the project. The changes ensure that the latest version of the `commonware-storage` library is used.
Version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L19-R19): Updated `commonware-storage` version from `0.0.3` to `0.0.4`.
* [`storage/Cargo.toml`](diffhunk://#diff-1bc5295720b3cef85cb02ee50bf34162eeabbbbac323d766e7faa38599da5d57L5-R5): Updated `commonware-storage` version from `0.0.3` to `0.0.4`.

[release] 11/6/24

---

cryptography/Cargo.toml
cryptography/src/bls12381/benches/partial_signature_aggregation.rs
cryptography/src/bls12381/benches/signature_aggregation.rs
cryptography/src/bls12381/benches/signature_verify_aggregation.rs
cryptography/src/bls12381/dkg/ops.rs
cryptography/src/bls12381/mod.rs
cryptography/src/bls12381/primitives/mod.rs
cryptography/src/bls12381/primitives/ops.rs
examples/vrf/src/handlers/vrf.rs

This pull request introduces several new benchmarking functions and refactors existing ones in the `cryptography` module, particularly focused on the BLS12-381 cryptographic operations. Additionally, it includes updates to documentation and test cases to reflect these changes.
* Added `benchmark_partial_signature_aggregation` in `cryptography/src/bls12381/benches/partial_signature_aggregation.rs` to benchmark partial signature aggregation.
* Added `benchmark_signature_verify_aggregation` in `cryptography/src/bls12381/benches/signature_verify_aggregation.rs` to benchmark signature verification with aggregation.
* Refactored `benchmark_signature_aggregation` in `cryptography/src/bls12381/benches/signature_aggregation.rs` to use a different set of messages and updated the aggregation logic. …

[cryptography/bls12381] Construct and Verify Aggregate Signatures

---

docs/blogs/commonware-cryptography.html
docs/style.css
examples/chat/README.md

This pull request addresses the following issues:
1. **Typos in `commonware-cryptography.html`:**
- Corrected the Discord link by removing redundant text (`Discord`).
2. **Duplicate CSS in `style.css`:**
- Removed the duplicate `.image-container` rule to streamline the stylesheet.
3. **Spelling Error in `README.md`:**
- Corrected "Synchonized" to "Synchronized" in the "Synchronized Friends" section.

[fix]: Address Typos and Remove Duplicate CSS Rules

---

examples/chat/src/main.rs
examples/vrf/src/main.rs
p2p/build.rs
p2p/src/authenticated/actors/peer/actor.rs
p2p/src/authenticated/actors/peer/ingress.rs
p2p/src/authenticated/actors/peer/mod.rs
p2p/src/authenticated/actors/router/actor.rs
p2p/src/authenticated/actors/spawner/actor.rs
p2p/src/authenticated/channels.rs
p2p/src/authenticated/config.rs
p2p/src/authenticated/metrics.rs
p2p/src/authenticated/mod.rs
p2p/src/authenticated/network.rs
p2p/src/authenticated/wire.proto
stream/src/placeholder/instance.rs

Fixes #186 
Also slightly touches the `split()` function in the `stream` crate to not return the maximum message size allowed

[p2p] Remove Chunking

---

runtime/src/deterministic.rs

Related: #180 
We need this to better cleanly deterministic "unclean shutdown" simulation. A more crude version of this approach (where the caller handled internal state) was tested here: https://github.com/commonwarexyz/monorepo/blob/bb8497a131e79ba04dfa2735c674860448bd2568/runtime/src/deterministic.rs

[runtime/deterministic] Expose Runtime `Recover` to Deterministically Simulate Restarts

---

p2p/src/authenticated/actors/dialer.rs
p2p/src/authenticated/actors/listener.rs
p2p/src/authenticated/actors/peer/actor.rs
p2p/src/authenticated/actors/spawner/actor.rs
p2p/src/authenticated/actors/spawner/ingress.rs
p2p/src/authenticated/network.rs
stream/src/public_key/connection.rs

- The cryptography is used only for the handshake authentication, the actual connection is agnostic to the crypto used
- Cleaned up some variable naming like `connection` that was used to refer to a `Config`

[stream] Remove need for specifying cryptography in `stream::public_key::Connection`

---

p2p/src/authenticated/actors/listener.rs
p2p/src/authenticated/actors/mod.rs
p2p/src/authenticated/network.rs
stream/src/lib.rs
stream/src/public_key/connection.rs
stream/src/public_key/handshake.rs
stream/src/public_key/mod.rs

Resolves: #181 
* Refactor `Connection` to avoid exposing `Handshake`.
* Use a reference to `runtime` in handshake verification to reduce cloning.
* Add comments to public structs and functions.

[stream] Initial `IncomingHandshake` Cleanup

---

p2p/src/authenticated/actors/peer/actor.rs

This mutualizes some duplicated code I found when reading `authenticated::actors::peer`.
Let me know if this is acceptable or not 👍  if it is, I could continue to look at the rest of the modified file.

[p2p::authenticated] : Reduce code duplication

---

codecov.yml

Merges to `main` sometimes look like they are failing because of `codecov`:
Source: https://docs.codecov.com/docs/commit-status#only_pulls

[CI] Only Post Statuses to PRs

---

consensus/src/simplex/mocks/application.rs
cryptography/src/bls12381/primitives/poly.rs
examples/vrf/src/handlers/utils.rs
p2p/src/authenticated/actors/tracker/address.rs
stream/src/public_key/handshake.rs

I ignored usages of `Vec::new()` in tests. You may think that using `std::mem::size_of::<u64>()` (etc.) is overkill. If so, fair enough. If you want, let me know and I'll change it to a good ol' `8` or `4`.
In some instances, you may feel that the extra code/clutter doesn't merit the performance gains. Again, fair enough. In those cases where we care about code aesthetics more than performance, I'd suggest doing, for example:
```rust
[
round.to_be_bytes().as_slice(),
dealer.to_be_bytes().as_slice(),
share,
]
.concat()
```
rather than
```rust
let mut payload = Vec::new();
payload.extend_from_slice(&round.to_be_bytes());
payload.extend_from_slice(&dealer.to_be_bytes());
payload.extend_from_slice(share);
payload
```
I believe these are semantically equivalent (don't quote me on that) and …

Use `Vec::with_capacity()` when we know vec capacity

---

cryptography/src/bls12381/benches/aggregate_public_keys.rs
cryptography/src/bls12381/benches/aggregate_signatures.rs
cryptography/src/bls12381/benches/aggregate_verify_multiple_messages.rs
cryptography/src/bls12381/benches/aggregate_verify_multiple_public_keys.rs
cryptography/src/bls12381/benches/bench.rs
cryptography/src/bls12381/benches/threshold_signature_recover.rs
cryptography/src/bls12381/mod.rs
cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/mod.rs
cryptography/src/bls12381/primitives/ops.rs
cryptography/src/bls12381/scheme.rs
examples/vrf/src/handlers/vrf.rs

Resolves: #279
Replaces: #282 
Unblocks: #289 
Cleans up naming, adds more comments/tests, and introduces PoP functionality for `bls12381`.

[cryptography/bls12381] Update `DST` + Single/Threshold Proof-of-Possession + Aggregate Verify for Multiple Public Keys (Single Message)

---

p2p/src/authenticated/actors/peer/actor.rs

Having an `Arc` in the type of `rate_limits` doesn't really buy us anything. We're just dereferencing it to get at the internal hashmap anyway.

remove unneeded `Arc` from parameter

---

Cargo.toml

Use rust's overflow-check build profile configuration option for release builds, so we panic on attempted integer overflows/underflows instead of wrapping.

[security] enable overflow checks in profile config (#291)

---

cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/scheme.rs
cryptography/src/ed25519.rs

Relates #287 
This adds a first test coming from https://github.com/ethereum/bls12-381-tests.
I don't know if I missed something when creating the BLS Scheme, but the generated signature is not the expected value provided by the vector.
When comparing the obtained `BigInt` (the one used to create the PrivateKey) and the `int` they use in the test, they look the same.
@patrick-ogrady do you see any reason why this could failed?

[cryptography/bls12381] vector tests

---

cryptography/src/bls12381/primitives/group.rs

The [latest IETF draft](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-05#section-5.1) updated `keygen` to satisfy the HKDF security analysis assumptions:
> KeyGen uses HKDF to generate keys. The security analysis of HKDF assumes that the salt value is either empty (in which case it is replaced by the all-zeros string) or an unstructured string. Versions of this document prior to number 4 set the salt parameter to "BLS-SIG-KEYGEN-SALT-", which does not meet this requirement. If, as is common, the hash function H is modeled as a random oracle, this requirement is obviated.
This PR updates the code to use `blst_keygen` (which uses the `v4` keygen algorithm) from `blst_keygen_v3` (which does not satisfy the assumptions).
While we could use `blst_keygen_v4_5` with a null …

[cryptography/bls12381] Migrate to `blst_keygen`

---

examples/chat/src/main.rs
examples/vrf/src/main.rs
p2p/src/authenticated/channels.rs
p2p/src/authenticated/mod.rs
p2p/src/authenticated/network.rs

The zstd library recognizes compression level values < 0 and > 255. This PR allows those compression levels to be used. If we'll never use these, feel free to close this.

nit: use Option<i32> instead of Option<u8> for compression level

---

cryptography/src/secp256r1.rs

@patrick-ogrady I figured out I missed your comment https://github.com/commonwarexyz/monorepo/pull/314#discussion_r1907653295.
This adds test for Scheme::verify with a signature embedding `r=0` and `s=0`.

[cryptography/secp256r1] add test verifying signature with r=0 and s=0

---

examples/chat/src/logger.rs
p2p/src/authenticated/actors/tracker/actor.rs
p2p/src/authenticated/config.rs
p2p/src/authenticated/mod.rs
p2p/src/lib.rs

Hello! I went through the code and fixed a few typos in the comments. Nothing major, but it should make things a bit easier to read and less distracting.
- **logger.rs**: "remaning" → "remaining".
- **actor.rs**: "propogating" → "propagating", "indicies" → "indices".
- **config.rs**: "messsage" → "message".
- **mod.rs**: "Recieve" → "Receive".
- **lib.rs**: "guranteed" → "guaranteed".

docs: Cleaned up typos in comments

---

storage/src/journal/storage.rs

File: storage/src/journal/storage.rs
Change:
- Old: If exact exceeds the size of an item
- New: If prefix exceeds the size of an item
The current documentation incorrectly references an 'exact' parameter in the warning comment of read_prefix method, while the method actually uses a 'prefix' parameter. This change aligns the documentation with the actual implementation to improve clarity and prevent confusion.

documentation parameter name in read_prefix method

---

cryptography/src/bls12381/primitives/mod.rs

Changed "duplicate eval" to "duplicate polynomial evaluation point"  to better explain what actually went wrong.

docs: improve DuplicateEval error message clarity

---

p2p/src/authenticated/ip.rs

This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected `re-implementation` to `reimplementation`
Corrected `Translat.` to `Translation`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

scripts/bump_versions.sh

Current file writing logic could misinterpret formatting symbols in the content array, leading to potential errors. To address this, I replaced the `printf` statement with a loop that processes each line individually.
This ensures that all lines are written correctly, regardless of their content.  
I also added a comment to explain the change, making it easier for others to understand the reasoning behind it.
This makes the script more robust and safer to use.  
LFG!

fix: Fix for File Writing Issue to Prevent Formatting Errors

---

consensus/build.rs

there’s no `Parent.digest` field defined in the corresponding `.proto` files, there’s nothing for the compiler to generate. As a result, both `"Parent.digest"` lines should be removed from the configuration.

Remove `Parent.digest` Lines

---

Cargo.lock
examples/aggregation/Cargo.toml
examples/aggregation/src/bn254.rs
examples/aggregation/src/handlers/orchestrator.rs
examples/aggregation/src/main.rs

To pass this verification onchain, we need to emit the low-level points: https://github.com/Layr-Labs/eigenlayer-middleware/blob/fe5834371caed60c1d26ab62b5519b0cbdcb42fa/src/BLSSignatureChecker.sol#L295-L334
For a log like:
```
aggregated signatures round=1737523641 msg="22a04120b1e80c0bb0b16512e66fd16745689201dbc1b8f55f5449e37e1f3e43" participants=["e3ef9067ae19997c04a0f49b058a7c76d65d08df3dc1aeea1a8337a0005c4904640ac749c216decd7dfa886ef81abf9a11227e2bd5c0ae0d83e2d0924bab1a8e", "e69df082e6758e798195d8c6360f5a8428206344c3d0f74b9ece86bd46c36a015248a1840edd49470eb94bb5b63bbda06ec70db4e6b81dc3a60329a1709fdf8f", "fba7c14ee7a32e66e6fa097ea5c2370efe8eb4714ba26981017602d62fffcd2ce44c73eed4c33c3d19cebb73ae4c22f1556d013137efc50d9979d051b5fd6503"] …
```

[examples/aggregation] Log points

---

cryptography/src/bls12381/dkg/ops.rs
cryptography/src/bls12381/primitives/ops.rs
runtime/src/tokio.rs

- Corrected "coeffcient-wise" to "coefficient-wise" in `ops.rs`.
- Corrected "Proof-of-Posession" to "Proof-of-Possession" in `ops.rs` for clarity.
- Fixed "mmaping" to "mapping" in `tokio.rs`.

Fix spelling errors in tokio.rs, ops.rs

---

.github/workflows/tests.yml
Cargo.lock
Cargo.toml
consensus/Cargo.toml
consensus/src/lib.rs
consensus/src/simplex/mocks/relay.rs
consensus/src/simplex/mod.rs
consensus/src/simplex/prover.rs
consensus/src/threshold_simplex/mocks/relay.rs
consensus/src/threshold_simplex/mod.rs
consensus/src/threshold_simplex/prover.rs
storage/Cargo.toml
storage/src/lib.rs

It can be VERY useful to use pre-existing proof verification logic from consensus/storage in WASM environments. This makes that possible (and adds a test to ensure forward-compatibility).

[CI] Add WASM Support for `consensus` and `storage`

---

consensus/src/simplex/prover.rs
consensus/src/threshold_simplex/prover.rs

This commit fixes a critical security vulnerability in the consensus proof
verification system where an attacker could cause integer overflow in signature
size calculations. The vulnerability could potentially lead to memory corruption
and consensus protocol manipulation.
The fix adds proper integer overflow checks using Rust's safe arithmetic
operations (checked_add and checked_mul) when calculating total signature sizes
during proof verification.
Security Impact:
- Prevents potential memory corruption from integer overflow
- Protects against maliciously crafted proofs
- Maintains consensus protocol integrity
Testing:
- Existing tests pass
- Edge cases with large signature counts now safely return None

fix: prevent integer overflow in consensus proof verification

---

storage/Cargo.toml
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/mem.rs
storage/src/mmr/mod.rs
storage/src/mmr/verification.rs

adds a forget() capability (+ tests) to the MMR that removes older nodes from memory without affecting the ability to generate inclusion proofs for remaining elements and any newly added elements.

[commonware-storage/mmr] add forgetting support to the in-mem mmr

---

storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/verification.rs

We don't need to include a separate `byte` to indicate how many hashes are included in a proof. We can infer this from the size of the proof itself.

[storage/mmr] Simplify Proof Serialization

---

consensus/src/simplex/verifier.rs
consensus/src/threshold_simplex/verifier.rs

In `consensus/src/simplex/verifier.rs`:
1. `verify_nullification`:
- "dropping finalization" -> "dropping nullification" (3 instances)
2. `verify_finalization`:
- "dropping notarization" -> "dropping finalization" (1 instance)
Debug messages were inconsistent with their verification functions. Each function should use messages that match its operation type (notarization/nullification/finalization) for better debugging and code clarity.
These are text-only changes that improve code maintainability without affecting functionality.

Update verifier.rs: Fix inconsistent debug messages

---

cryptography/src/bls12381/benches/signature_generation.rs
cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/ops.rs

To further speed up verification, we can use the negated generator constant for `g1` instead of negating `hm` at runtime.

[cryptography/bls12381] Use negated generator constant

---

consensus/src/simplex/mocks/application.rs
consensus/src/simplex/mod.rs
consensus/src/simplex/prover.rs
consensus/src/threshold_simplex/mocks/application.rs
consensus/src/threshold_simplex/mod.rs
consensus/src/threshold_simplex/prover.rs
cryptography/src/ed25519/mod.rs
cryptography/src/ed25519/scheme.rs
cryptography/src/lib.rs
cryptography/src/secp256r1/mod.rs
cryptography/src/secp256r1/scheme.rs
cryptography/src/sha256/mod.rs
examples/bridge/src/bin/indexer.rs
examples/bridge/src/bin/validator.rs
examples/log/src/main.rs
storage/src/mmr/hasher.rs
storage/src/mmr/verification.rs

To simplify the `Hasher` trait, we add `Sized` to `Digest` instead of using the const `DIGEST_LENGTH`. This doesn't impact whether or not the length is known at compile-time.

[cryptography/hasher] Remove `DIGEST_LENGTH` const

---

storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/mem.rs
storage/src/mmr/mod.rs
storage/src/mmr/verification.rs

- add ability to initialize an mmr from a vector of nodes
- add ability to request individual nodes
- made proof generation dependent only on a simple Mmr trait instead of a specific implementation
- clarified some of the pruning documentation
- fixed edge case bug in ensuring position validity for proof generation after pruning
- removed ability to forget to arbitrary point in history since it doesn't properly detect how proving is affected by it. will re-work forgetting in a subsequent PR (tracking issue: https://github.com/commonwarexyz/monorepo/issues/459)

[commonware-storage/mmr/mem] API extensions to support generic proof generation + forgetting tweaks

---

cryptography/src/bls12381/mod.rs
cryptography/src/bls12381/scheme.rs
cryptography/src/ed25519/mod.rs
cryptography/src/ed25519/scheme.rs
cryptography/src/lib.rs
cryptography/src/secp256r1/mod.rs
cryptography/src/secp256r1/scheme.rs
cryptography/src/sha256/mod.rs

Related: #447 
Because these types aren't exported, the docs look like this:
It may also be nice to take advantage of certain functionality specific to an implementation (not currently done but could be).

[cryptography] Fix Exports of `PrivateKey`, `PublicKey`, `Signature`

---

storage/Cargo.toml
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/mem.rs
storage/src/mmr/mod.rs
storage/src/mmr/verification.rs

get_node needs to be async to support backing an MMR with a Journal

[commonware-storage/mmr] Make get_node() in the MMR Storage trait async

---

storage/src/mmr/mem.rs
storage/src/mmr/verification.rs

Make get_node() return a full digest instead of a reference, since there is no reference to return for disk-backed MMRs.

[commonware-storage/mmr] make get_node() return a Digest instead of &Digest

---

storage/src/mmr/benches/append.rs
storage/src/mmr/benches/append_additional.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/mem.rs
storage/src/mmr/verification.rs

This PR requires the caller to provide a reusable hasher for efficiency rather than maintaining one inside the MMR. This avoids interior mutability issues that (for example) required making methods such as root() mutable.

[commonware-storage/mmr] remove reusable hasher from mem::Mmr to avoid interior mutability concerns

---

storage/src/journal/fixed.rs
storage/src/journal/mod.rs

The MMR will need to be able to rewind the journal to back up to a valid state after a partial write failure.

[commonware-storage/mmr] add rewind function to fixed-item journal

---

storage/src/mmr/iterator.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/verification.rs

Addresses https://github.com/commonwarexyz/monorepo/issues/459

[commonware-storage/mmr] less restrictive in-mem-mmr forgetting

---

Cargo.lock
Cargo.toml
broadcast/Cargo.toml
broadcast/build.rs

Fixes an issue with the docs and build process
Also bump the version to `0.0.3`

[broadcast::linked] Allow experimental `optional` field in proto3

---

broadcast/src/linked/signer/actor.rs
consensus/src/simplex/mocks/application.rs
consensus/src/simplex/mocks/conflicter.rs
consensus/src/simplex/mocks/nuller.rs
consensus/src/threshold_simplex/mocks/application.rs
consensus/src/threshold_simplex/mocks/conflicter.rs
consensus/src/threshold_simplex/mocks/nuller.rs
examples/log/src/application/actor.rs
examples/vrf/src/handlers/arbiter.rs
examples/vrf/src/handlers/contributor.rs
examples/vrf/src/handlers/vrf.rs
p2p/src/authenticated/actors/router/actor.rs
p2p/src/authenticated/actors/spawner/actor.rs
p2p/src/authenticated/actors/tracker/actor.rs
p2p/src/authenticated/network.rs
p2p/src/simulated/network.rs
runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/tokio.rs

Replaces: #521 
While context reuse won't cause any issues atm, we should prevent it now for the day it does.

[runtime] Alternative approach to `spawn_ref`

---

storage/src/mmr/iterator.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/mod.rs

Provides the journaled MMR with the same pruning capabilities of the in-memory MMR, guaranteeing recovery from any partial write scenarios.
Also cleans up some obsolete language (retained vs remembered, pruned vs forgotten)

[commonware-storage/journaled] pruning support for journal-backed MMR

---

storage/src/mmr/mod.rs
storage/src/mmr/verification.rs

This PR separates out the process of generating the positions of the required elements from the process of fetching those elements.  It also improves precision of some of the language in the comments.

[commonware-storage/mmr] proof generation function that returns only the required elelement positions

---

deployer/src/ec2/utils.rs

If the deployment of a binary fails, it may be in `failed` status after `stop` is called.

[deployer] Consider `failed` status the same as `inactive`

---

consensus/src/simplex/actors/voter/actor.rs
consensus/src/simplex/actors/voter/mod.rs
consensus/src/simplex/config.rs
consensus/src/simplex/engine.rs
consensus/src/simplex/mod.rs
consensus/src/threshold_simplex/actors/voter/actor.rs
consensus/src/threshold_simplex/actors/voter/mod.rs
consensus/src/threshold_simplex/config.rs
consensus/src/threshold_simplex/engine.rs
consensus/src/threshold_simplex/mod.rs
examples/bridge/src/bin/validator.rs
examples/log/src/main.rs

Related: https://github.com/commonwarexyz/alto/issues/15
This PR allows us to retain a healthy buffer of view artifacts near tip without losing responsiveness to offline participants (that we would otherwise try to skip).

[consensus] Separate `skip_timeout` and `acitvity_timeout`

---

deployer/src/ec2/services.rs

```
msg="validating config" err="CONFIG ERROR: invalid schema config: validating period_config: tsdb must always have periodic config for index set to 24h"
```

[deployer] Revert loki configuration change

---

storage/src/mmr/mod.rs
storage/src/mmr/verification.rs

Separates out peak reconstruction from root hash comparison and introduces specific error types for missing vs extra hashes in the proof data.

[commonware-storage/mmr] minor refactor of proof verification

---

examples/flood/src/bin/flood.rs
runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/tokio.rs
runtime/src/utils.rs

[runtime] Add support for `spawn_blocking`

---

broadcast/src/linked/engine.rs
broadcast/src/linked/mod.rs
consensus/src/threshold_simplex/actors/voter/actor.rs
consensus/src/threshold_simplex/mod.rs
consensus/src/threshold_simplex/prover.rs
consensus/src/threshold_simplex/verifier.rs
cryptography/src/bls12381/benches/aggregate_verify_multiple_messages.rs
cryptography/src/bls12381/dkg/mod.rs
cryptography/src/bls12381/mod.rs
cryptography/src/bls12381/primitives/ops.rs
cryptography/src/bls12381/primitives/poly.rs
examples/bridge/src/bin/validator.rs

On my machine, it takes ~641 µs to verify a single BLS12-381 signature but only ~733 µs to verify an aggregate signature over two BLS12-381 from the same public key.
```
bls12381::signature_verification/ns_len=9 msg_len=32
time:   [617.53 µs 625.76 µs 641.84 µs]
bls12381::aggregate_verify_multiple_messages/conc=1 msgs=2
time:   [732.63 µs 733.84 µs 735.53 µs]
```

[consensus/threshold-simplex] Employ aggregate verification when possible

---

stream/src/public_key/mod.rs
stream/src/public_key/nonce.rs

- Just put everything in to a `u128`
- Initialized to `1` or `0` based on boolean
- Increments by 2 (preserving the least-significant bit)
- Overflows past 12 bytes (Nonce is 12 bytes long)
- Deserializes least significant 12 bytes
Simpler and more maintainable. Might be faster, might not be. Increases the overflow bound by 2^15 as many increments. Previously if you incremented the nonce every single nanosecond, you would only be able to do-so for 38 million years. Now this should be good for about 1.2 trillion years. 91 times the age of the universe should be enough for anyone

[stream] Simplify nonce logic

---

Cargo.lock
codec/src/buffer.rs
codec/src/codec.rs
codec/src/error.rs
cryptography/Cargo.toml
cryptography/src/bls12381/scheme.rs
cryptography/src/ed25519/scheme.rs
cryptography/src/secp256r1/scheme.rs
cryptography/src/sha256/mod.rs
resolver/Cargo.toml
resolver/src/p2p/mocks/key.rs
utils/Cargo.toml
utils/src/array/fixed_bytes.rs
utils/src/array/mod.rs
utils/src/array/u64.rs

A change that allows other crates to start using `Codec` and `FixedCodec` more easily since `Array` implements `Codec` and `FixedCodec`. Eventually we will remove the use of `SizedSerialize` and several other parts of the `Array` trait. For example, we should remove the requirement of `Array` to implement `TryFrom` for `Vec<u8>` and `&Vec<u8>`.
`&Vec<u8>` is redundant since `Vec<u8>` dereferences to `&[u8]`, and `Vec<u8>` is handled by converting to Bytes (transfers ownership to `Bytes` without making a copy).
Will make #593 easier
Also the first step in #622

[utils] `Array` must implement `FixedCodec`

---

storage/src/mmr/mod.rs
storage/src/mmr/mutable.rs
storage/src/mmr/verification.rs

Initial mutable mmr implementation with minimal functionality. Supports proving update history but not proving of which value is current for a given key.  Does not currently implement compaction or persistence.

[commonware-storage/mmr] Basic mutable k/v store - part 1

---

p2p/src/authenticated/actors/tracker/actor.rs

- Instead of rounding up to the nearest multiple of 8, `required_bytes` was adding an extra whole byte for multiples of 8
- The naming is also wrong, it's actually the number of required bits, so I changed the name :)

[p2p] Fix bug with tracker bitvec

---

storage/src/mmr/iterator.rs
storage/src/mmr/mem.rs

A few minor cleanups:
1. Some of the MMR helpers can be `const`, so might as well mark them as such.
2. Remove a little boilerplate in `get_node`.
3. Destructure tuple and `peak_pos` instead of `peak.0`

MMR: nits; make functions const

---

storage/src/journal/fixed.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/iterator.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/mod.rs
storage/src/mmr/verification.rs
utils/src/array/mod.rs
utils/src/array/prefixed_u64.rs

- Store an additional O(log2(n)) historical nodes, which we refer to as _pinned_, to guarantee any current & future retained node is provable after pruning. This allows removing of the "min provable position" related ugliness.
- `prune_all` behavior is changed to prune everything instead of leaving behind a single digest, simplifying boundary conditions.
- improve consistency of terminology/naming

[commonware-storage/mmr] Simplify & improve MMR pruning behavior

---

storage/src/mmr/mutable.rs

Support for raising an "inactivity floor" beneath which all operations are inactive and can be pruned without affecting ability to rederive the state of the K/V store.

[commonware-storage/mutable] compaction of inactive operations

---

p2p/src/authenticated/actors/tracker/actor.rs
storage/src/bmt/mod.rs
storage/src/mmr/mutable.rs
utils/src/lib.rs

**Summary**
- Replaced manual `(x + 1) / 2` and `(x + 7) / 8` with `.div_ceil(...)`, addressing Clippy’s `manual_div_ceil`.
- Fixed doc comments with excessive indentation, resolving `doc_overindented_list_items`.
- Replaced the `Ok(...) => Some(...), Err(...) => None` pattern with `.ok()`, removing `manual_ok_err`.
**Why**
- Keeps the code clean and warning-free under Clippy’s strict checks (`-D warnings`).
- Improves readability (DOC comments), correctness (using built-in div_ceil), and consistency with Rust best practices.
**Testing**
- Verified locally that `cargo clippy --all -- -D warnings` passes with no new warnings.
- No functional changes — purely stylistic and lint-related improvements.

Fix Clippy warnings: doc overindented list items, manual div_ceil, manual_ok_err

---

codec/src/codec.rs
storage/src/mmr/mod.rs
storage/src/mmr/mutable.rs
storage/src/mmr/operation.rs
storage/src/mmr/operation_array.rs

Moves Operation and Type types to their own module where they implement the Array trait so that we can persist them using a fixed-item-length journal.

[commonware-storage/mutable] make operation type an Array

---

storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs

This functionality will let us implement rollback in the mutable mmr K/V store.

[commonware-storage/mmr/journaled] Add rewind capability to journaled MMR

---

storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/mutable.rs
storage/src/mmr/operation.rs

This PR makes the mutable MMR K/V store durable through:
- replacing the VectorDeque log of operations with a journal,
- replacing the in-memory MMR with a journaled MMR,
- implementing snapshot generation on startup via log replaying, and
- implementing a recovery policy in the event of inconsistency between the persistent state of the log and the persistent state of the MMR.
- fix bug in journaled MMR orphaned leaf recovery, update tests to catch regressions.
The PR also changes/renames the floor operation to "commit" and modifies its semantics. Any operations following the last commit op are rolled back on recovery.  Inactivity floor raising and syncing are now private methods, with commit() the only public method for enforcing a specific recoverable state and discarding of inactive …

[commonware-storate/mutable] A durable mutable MMR K/V store

---

deployer/src/ec2/update.rs

`ip` is already a `String`, so there's no need to call `.clone()` before moving it into the `async move` block.
The value is automatically moved, making the extra clone redundant.
Removed the unnecessary `clone()` to simplify the code.

[deployer] remove unnecessary clone of `ip`

---

storage/src/adb/any.rs
storage/src/adb/mod.rs
storage/src/adb/operation.rs
storage/src/lib.rs
storage/src/mmr/mod.rs

- adb module stands for "authenticated database"
- renamed the "mutable mmr" to the `Any` variant of an authenticated database based on its authentication capabilities (being able to prove a key had any of its historically assigned values).

[commonware-storage/mmr/mutable] move mmr-based kv store from the mmr module to a new adb module

---

examples/log/src/gui.rs

Timestamps in whole gui in `log` example is getting showing in UTC. This change shows timestamp with timezone local to OS.

feat(examples): show timestamps in local timezone for log example

---

.github/workflows/benchmark.yml

All other workflow files in the repo already use actions/checkout@v4. This one was still on v3, so I updated it for consistency.
Also, GitHub recommends using the latest major version. Here's the official migration guide for reference:
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

Update checkout action to v4

---

storage/src/adb/any.rs
storage/src/archive/storage.rs
storage/src/index/mod.rs
storage/src/index/storage.rs

- updates storage::index with unsafe iterators allowing them to insert and update values during iteration (UpdateValueIterator and DeleteValueIterator respectively). 
- storage::index's insert operation is now guaranteed to always insert the new element at the head of the list for more predictable ordering and providing a more LRU-like behavior.
- updates storage::adb::any to use these constructs in order to reduce hashmap lookups for delete and update operations.
- fix bug in storage::adb::any pertaining to replaying of delete operations that could result in an incorrect snapshot on restart, and added test to prevent regression.
Addresses the concerns from this issue: https://github.com/commonwarexyz/monorepo/issues/682

[commonware-storage/index] allow the mutable iterator to delete & insert efficiently

---

codec/src/extensions.rs
codec/src/types/map.rs
codec/src/types/mod.rs

Fixes #708 
Keys must be sorted (ascending). This provides deterministic guarantees around the encoding.

[Codec] Add `HashMap` implementation

---

consensus/src/simplex/mod.rs
consensus/src/threshold_simplex/mod.rs
cryptography/src/bls12381/dkg/mod.rs
utils/src/lib.rs

Previously the quorum calculation could return values that were `<= (n*2/3)`

[utils] fix `quorum` calculation for unaligned `n`

---

p2p/src/authenticated/actors/tracker/actor.rs
p2p/src/authenticated/actors/tracker/ingress.rs

Based on collected metrics, this would reduce the number of spawned tasks by ~99% in a standard instance.

[p2p/authenticated] use `try_send` for `Drop`

---

storage/src/mmr/bitmap.rs
storage/src/mmr/mem.rs

Support the ability to prune historical bits from the bitmap and the tree nodes over them, except those that must be maintained to support authentication of any retained bit.

[commonware-storage/mmr/bitmap] pruning support for the authenticated bitmap

---

storage/src/mmr/hasher.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs

Change the MMR element type from Digest to &[u8] since any type that can be represented as a byte slice will work, not just digests.  This will allow applications to avoid unnecessary hashing of elements to convert them to digests before adding them to the MMR.

[commonware-storage/mmr] change mmr element type to &[u8]

---

p2p/src/authenticated/types.rs

In most examples, channel is a low number. Since channel is sent with each message, we may save a decent amount of bandwidth (up to 3 bytes for every single network message)

[p2p] encode u32 channel as varint

---

storage/src/mmr/bitmap.rs

- decouples the chunk_size of an authenticated bit map from the digest size of the hasher
- changes underlying structure from a Vec<u8> to a VecDequeue<[0u8; chunk_size]> for constant-time pruning.

[commonware-storage/bitmap] use VecDeque for authenticated bitmap bits

---

storage/src/journal/fixed.rs

Fixed a small typo in a comment within fixed.rs where "epty" was incorrectly written instead of "empty". This change improves code readability and documentation accuracy.

Fix typo in comment: "epty" -> "empty"

---

storage/src/adb/any.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs

Consistently use "pruned_to_pos" instead of "oldest_retained_pos" when we are referring to the pruning point, which may not necessarily be the position of a valid node: when everything has been pruned, it will equal the size of the structure.

[commonware-storage][adb/mmr] expose pruned_to_pos as method separate from oldest_retained_pos

---

Cargo.lock
Cargo.toml
broadcast/Cargo.toml
codec/Cargo.toml
consensus/Cargo.toml
cryptography/Cargo.toml
deployer/Cargo.toml
examples/bridge/Cargo.toml
examples/chat/Cargo.toml
examples/flood/Cargo.toml
examples/log/Cargo.toml
examples/vrf/Cargo.toml
macros/Cargo.toml
p2p/Cargo.toml
resolver/Cargo.toml
runtime/Cargo.toml
storage/Cargo.toml
stream/Cargo.toml
utils/Cargo.toml

```
git diff 3300f012094d9f5586af11d31354a903cee8dd88 --stat
.github/workflows/benchmark.yml                    |    2 +-
Cargo.lock                                         |  138 +-
Cargo.toml                                         |   25 +-
broadcast/Cargo.toml                               |    2 +-
broadcast/src/buffered/config.rs                   |    6 +-
broadcast/src/buffered/engine.rs                   |   18 +-
broadcast/src/buffered/ingress.rs                  |    4 +-
broadcast/src/buffered/mocks.rs                    |   18 +-
broadcast/src/buffered/mod.rs                      |    3 +-
broadcast/src/lib.rs                               |    6 +-
codec/Cargo.toml                                   |    2 +-
codec/src/codec.rs                                 |  163 +- …
```

[release] 4-21-25

---

consensus/src/ordered_broadcast/mod.rs
consensus/src/threshold_simplex/actors/voter/mod.rs
consensus/src/threshold_simplex/mod.rs
cryptography/Cargo.toml
cryptography/src/bls12381/benches/dkg_recovery.rs
cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
cryptography/src/bls12381/dkg/mod.rs
cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/poly.rs
cryptography/src/bls12381/scheme.rs
cryptography/src/ed25519/scheme.rs
cryptography/src/secp256r1/scheme.rs
examples/vrf/src/handlers/contributor.rs

It turns out just implementing `Zeroize` doesn't actually do anything. You need to implement `Drop` and call `.zeroize()`.

[cryptography] Always Implement and Drop `Zeroize`

---

runtime/src/lib.rs
runtime/src/mocks.rs
runtime/src/storage/tokio.rs

Instead of swallowing IO errors from blob file IO, wrap/propgate them to enable easier failure diagnosis.
This required removing PartialEq trait from the commonware-runtime Error enum, but as I understand it, PartialEq for errors is non-idiomatic, and using maches! macro is preferrable to ==.

[commonware-runtime/storage] wrap blob io errors instead of swallowing them

---

runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/storage/audited.rs
runtime/src/storage/memory.rs
runtime/src/storage/metered.rs
runtime/src/storage/mod.rs
runtime/src/storage/tokio.rs
runtime/src/tokio/runtime.rs
storage/src/archive/mod.rs
storage/src/journal/fixed.rs
storage/src/journal/variable.rs
storage/src/metadata/mod.rs
storage/src/metadata/storage.rs
storage/src/mmr/journaled.rs

[runtime/storage] remove `Blob::len()`; add blob length to `Storage::open` return type

---

runtime/src/benchmarks/tokio.rs
storage/src/journal/benches/bench.rs
storage/src/journal/benches/fixed_append.rs
storage/src/journal/benches/fixed_read_random.rs
storage/src/journal/benches/fixed_read_sequential.rs
storage/src/journal/benches/fixed_replay.rs
storage/src/journal/fixed.rs

- Write random-read benchmark journal only once to improve overall runtime.
- Rename commonware_runtime::benchmarks::tokio::Executor to Runner.
- Also fixed recently introduced hang in the replay benchmark due to the concurrency value rounding down to 0.

[commonware-runtime/commonware-storage benches] reuse large journal across benchmarks, fix Runner naming

---

storage/src/mmr/iterator.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/verification.rs

Simplifies the pinned nodes computation based on the observation that the pinned node set can be fully determined by the pruning boundary alone. (Prior algorithm also involved the size of the MMR being pruned.)
Also changes the API to return an iterator instead of a collection.

[commonware-storage/mmr/verfication] simplify pinned nodes computation

---

storage/src/mmr/bitmap.rs
storage/src/mmr/journaled.rs

This allows restoring the state of an authenticated bitmap by "replaying" only the retained (unpruned) elements.
Also fixes bug where we weren't pruning the mem_mmr as much as we could have been because of failure to translate a chunk_position into the appropriate leaf_position.
In the process of working on this PR I learned the pinned_nodes computation [can be simplified](https://github.com/commonwarexyz/monorepo/pull/810) to not depend on the size of the MMR, and instead only the pruning boundary. That will simplify this PR nicely as the bitmap won't have to maintain its own set of pinned nodes.

[commonware-storage/mmr/bitmap] add persisting of pruned portion of authenticated bitmap

---

Cargo.lock
Cargo.toml
broadcast/Cargo.toml
codec/Cargo.toml
consensus/Cargo.toml
cryptography/Cargo.toml
deployer/Cargo.toml
examples/bridge/Cargo.toml
examples/chat/Cargo.toml
examples/flood/Cargo.toml
examples/log/Cargo.toml
examples/vrf/Cargo.toml
macros/Cargo.toml
p2p/Cargo.toml
resolver/Cargo.toml
runtime/Cargo.toml
storage/Cargo.toml
stream/Cargo.toml
utils/Cargo.toml

```
git diff 93a6a12e0d065e4d34fa40fdbc195b2e4fc8f039 --stat
.github/actions/setup/action.yml                   |  23 -
.github/workflows/benchmark.yml                    |   2 +-
Cargo.lock                                         |  82 ++-
Cargo.toml                                         |  25 +-
broadcast/Cargo.toml                               |   2 +-
broadcast/src/buffered/config.rs                   |   4 +-
broadcast/src/buffered/engine.rs                   |  94 ++-
broadcast/src/buffered/ingress.rs                  |  78 ++-
broadcast/src/buffered/metrics.rs                  |   7 +
broadcast/src/buffered/mod.rs                      | 108 ++--
broadcast/src/lib.rs                               |  11 +-
codec/Cargo.toml                                   |   2 +- …
```

[release] 4-25-25

---

storage/src/index/mod.rs
storage/src/index/storage.rs
storage/src/index/translator.rs

This pull request refactors the `Translator` trait and its usage in the `Index` structure to improve performance and flexibility by incorporating the `BuildHasher` trait. Additionally, it introduces a new `IdentityHasher` implementation and updates the `cap` translators to use minimal integer types. Below are the key changes grouped by theme:
* Updated the `Translator` trait to implement `BuildHasher` and revised its documentation to clarify the performance implications of non-uniform key distributions. The `Key` type now must implement `Hash` for compatibility with `HashMap`. (`storage/src/index/mod.rs`, [storage/src/index/mod.rsL18-R31](diffhunk://#diff-2dd4d6b8fcf070743f9f820bdd9f212fee2852197f80474e097c2394179ce46dL18-R31))
* Modified the `Index` structure to include the `Translator` …

[storage/index] Optimize `Translator` Usage

---

consensus/src/ordered_broadcast/types.rs
consensus/src/simplex/types.rs
consensus/src/threshold_simplex/types.rs
cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/poly.rs
examples/bridge/src/types/inbound.rs
examples/vrf/src/handlers/wire.rs
p2p/src/authenticated/types.rs
storage/src/archive/mod.rs
storage/src/archive/storage.rs
stream/src/public_key/handshake.rs

Fixes #765 
Also fixes some other types that should be varint instead in:
- `cryptography`
- `examples`
- `p2p`
- `stream`

[consensus] primitive types encoded as varints

---

runtime/src/deterministic.rs
runtime/src/tokio/runtime.rs
runtime/src/utils.rs

These backticks aren't needed, and I don't see them used this way in other libraries.

[runtime] nit: remove unneded ` from [doc::links]

---

p2p/src/utils/requester/metrics.rs
p2p/src/utils/requester/requester.rs
resolver/src/p2p/engine.rs
resolver/src/p2p/fetcher.rs
runtime/src/telemetry/metrics/status.rs

On `INFO`, 99% of logs come from `resolver` "failed to send" `WARN` logs (we start making requests before network connections are fully established).
This PR reduces per-request logging largely to `DEBUG` (and adds a metric to better track failed request creation).

[resolver] Use Metrics, Not `WARN` Logs to Communicate Errors

---

storage/src/adb/any.rs
storage/src/adb/mod.rs
storage/src/mmr/bitmap.rs

- moved log replaying into its own (non-pub) function where a bitmap can be provided to efficiently recover the active operation set.
- extend methods that update state to optionaly return the "old" locations of operations that have flipped from active to inactive.
- public API remains unchanged, though some private fns changed to pub(crate) for use by the upcoming current adb variant.
- somewhat unrelated to the above, but also makes the Index's Translator a parameter instead of fixing it at EightCap.

[commonware-storage/adb/any] extend adb::any API to support bitmap maintenance

---

runtime/src/deterministic.rs
runtime/src/storage/audited.rs

This PR replaces the various helper functions inside `Auditor` with `event`, which allows for any method to add its result to the auditor without needing its own helper.

[runtime] Generalize auditor to work over any payload

---

storage/src/mmr/bitmap.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/verification.rs

This is an artifact over previously relying on blob.size().

[storage/mmr/verification] remove async from verification::Storage trait's size() fn

---

runtime/src/lib.rs
runtime/src/network/metered.rs
runtime/src/network/mod.rs
runtime/src/network/tokio.rs
runtime/src/tokio/runtime.rs

This PR:
* Adds a new `mod network` inside `commonware_runtime`
* Adds 2 `commonware_runtime::Network` implementations
* One is in `metered.rs`. It wraps another `Network` to track metrics.
* The other is `tokio.rs` which uses tokio for network IO.
* Adds a `network` field to `Context` which is a `MeteredNetwork<TokioNetwork>` and has the same functionality as before

[runtime] Separate networking into its own module

---

.github/workflows/coverage.yml

Bump `codecov/codecov-action` from v4 to v5 to use the new Codecov Wrapper, keeping the workflow on the latest supported major version.
[Codecov GitHub Action – v5 release notes](https://github.com/codecov/codecov-action#v5-release)

Update Codecov action to v5

---

.github/actions/setup/action.yml
.github/workflows/benchmark.yml
.github/workflows/coverage.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
consensus/src/ordered_broadcast/mod.rs
consensus/src/simplex/mod.rs
consensus/src/threshold_simplex/mod.rs
p2p/src/authenticated/mod.rs
storage/src/archive/mod.rs

I was getting annoyed with our CI latency, so I put some elbow grease in and:
* broke tests into "lint", "slow", "fast" (all run concurrently now)
* added a caching layer around `rustc` via `sccache`
* changed how we cache cargo data
As a result:
* `Lint` is ~40% faster
* `Fast` takes ~5 minutes (old tests used to take ~20 minutes or so to get any feedback)
*****
This pull request introduces several updates to the CI workflows and test suite. The changes focus on improving caching mechanisms, simplifying workflow configurations, and enhancing test coverage and determinism. Additionally, new test cases and configurations have been added to the consensus module.
* [`.github/actions/setup/action.yml`](diffhunk://#diff-9fb8259afcb532c9556e2d41ae1ee97cf6de54b486cef93a7ef1bf39433fa530L2-R37): …

[consensus] Add "1k" Run + Move "slow" tests to `ignored`

---

storage/src/index/mod.rs
storage/src/index/storage.rs

- remove collisions counter, since the metric of interest is rate of collisions, not total (which we can compute from the new keys/items metric)
- Also reduce Trait clutter by taking advantage of fact that Eq implies PartialEq

[storage/index] remove collisions metric & unnecessary PartialEq trait declarations

---

Cargo.lock
Cargo.toml
broadcast/Cargo.toml
codec/Cargo.toml
consensus/Cargo.toml
cryptography/Cargo.toml
deployer/Cargo.toml
examples/bridge/Cargo.toml
examples/chat/Cargo.toml
examples/flood/Cargo.toml
examples/log/Cargo.toml
examples/vrf/Cargo.toml
macros/Cargo.toml
p2p/Cargo.toml
resolver/Cargo.toml
runtime/Cargo.toml
storage/Cargo.toml
stream/Cargo.toml
utils/Cargo.toml

* Layered modules: `network::{deterministic, audited, metered, tokio}`.
* `Context` & Tokio runtime now compose these layers ⇒ auditing hooks, per-connection metrics, time-outs.
* New helper type alias: `ListenerOf<N>`; `SinkOf` / `StreamOf` unchanged.
* Added Prometheus **`keys`** and **`items`** gauges; removed `collisions` counter.
* `Index::len()/is_empty()` → **`keys()`** (breaking).
* `Cursor` rewritten—safer phase machine.
* Replaced opaque byte blob with explicit `Operation::{Deleted, Update, Commit}`.
* Helpers `to_key()` / `to_value()` now return `Option<&…>`; `Type` enum removed (breaking).
---
| Change              | Detail                                                                                                                               |
| ------------------- | …

[release] v0.0.50

---

cryptography/src/bls12381/dkg/ops.rs
cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/ops.rs
cryptography/src/bls12381/primitives/poly.rs

Resolves: #719 
Replaces: #720 
Replaces: #731 
```
bls12381::dkg_reshare_recovery/conc=1 n=5 t=4
time:   [688.29 µs 694.30 µs 705.34 µs]
change: [-27.088% -26.186% -25.131%] (p = 0.00 < 0.05)
bls12381::dkg_reshare_recovery/conc=2 n=5 t=4
time:   [377.00 µs 378.26 µs 379.67 µs]
change: [-24.635% -24.344% -24.030%] (p = 0.00 < 0.05)
bls12381::dkg_reshare_recovery/conc=4 n=5 t=4
time:   [244.37 µs 246.40 µs 247.75 µs]
change: [-22.278% -20.925% -19.671%] (p = 0.00 < 0.05)
bls12381::dkg_reshare_recovery/conc=8 n=5 t=4
time:   [298.68 µs 301.99 µs 305.24 µs]
change: [-20.392% -18.243% -16.064%] (p = 0.00 < 0.05)
bls12381::dkg_reshare_recovery/conc=1 n=10 t=7
time:   [1.7400 ms 1.7421 ms 1.7452 ms]
change: [-38.047% -37.527% -36.903%] (p = 0.00 < 0.05)
bls12381::dkg_reshare_recovery/conc=2 …
```

[crypotgraphy/bls12381] Migrate to Pippenger's Algorithm (MSM)

---

cryptography/src/bls12381/primitives/group.rs

remove redundant word in comment

chore: remove redundant word in comment

---

docs/blogs/threshold-simplex.html

Description
- fix /blogs/many-to-many-interop.html → /blogs/threshold-simplex.html
- docs-only, no code changes
All files verified; link updated.

docs: replace outdated Commonware interop article link

---

deployer/src/ec2/authorize.rs
deployer/src/ec2/create.rs
deployer/src/ec2/destroy.rs
deployer/src/ec2/mod.rs
deployer/src/ec2/update.rs

During long-running tests, `/tmp` rarely persists long-enough to be useful.

[deployer] use `$HOME` for deployer artifacts

---

codec/src/types/bytes.rs
codec/src/types/map.rs
codec/src/types/net.rs
codec/src/types/primitives.rs
codec/src/types/tuple.rs
codec/src/types/vec.rs
codec/src/varint.rs

Fixes #841 
Also fixes a bug due to a misunderstanding about the [`to_bits`](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.to_bits) method on `Ipv4Addr/Ipv6Addr`. I thought the resulting integer VALUE was dependent on the endianness of the platform, and so was using `u32::to_be` to modify the bits. However, this understanding was incorrect.
This is shown in the example at the link above. Regardless of platform:
```
let addr = Ipv4Addr::new(0x12, 0x34, 0x56, 0x78);
assert_eq!(0x12345678, addr.to_bits());
```
The value is consistent regardless of native endianness, it is just saying that the octets are always stored big-endian in memory, so the memory layout of the resulting `u32` from `to_bits()` may not have the same memory layout. This bug resulted in inconsistent …

[codec] Add conformity tests

---

runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/telemetry/metrics/mod.rs
runtime/src/telemetry/metrics/status.rs
runtime/src/telemetry/metrics/task.rs
runtime/src/tokio/runtime.rs
runtime/src/utils/handle.rs
runtime/src/utils/mod.rs

`spawn_blocking` is meant for blocking tasks that finish on their own (using a shared thread pool). This PR adds support for spawning long-lived, blocking tasks that don't consume threads from the shared thread pool (recommended against doing in the `tokio` docs: https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html).

[runtime] Add Support for `spawn_blocking(dedicated)` + Pass `Context` to `spawn_blocking`

---

consensus/src/simplex/mocks/conflicter.rs
consensus/src/threshold_simplex/mocks/conflicter.rs
cryptography/src/lib.rs
cryptography/src/sha256/mod.rs
storage/src/bmt/benches/build.rs
storage/src/bmt/benches/prove_single_element.rs
storage/src/mmr/benches/append.rs
storage/src/mmr/benches/append_additional.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs

Moves `fn random<R: RngCore + CryptoRng>(rng: &mut R) -> Self;` to `Digest` trait. It felt odd that the Hasher was responsible for making a random hash rather than the hash.

[crypto] move `random` method to Digest trait

---

runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/macros.rs
runtime/src/spawn_macros.rs
runtime/src/tokio/runtime.rs

Replaces: #960 
Resolves: #958 
- factor out metrics setup macro for spawners
- include Label creation inside macro
- use new macro in deterministic and tokio runtimes

[runtime] Reduce Duplicate Metrics Usage (with `spawn_metrics!`)

---

storage/src/mmr/bitmap.rs
storage/src/mmr/mod.rs
storage/src/mmr/verification.rs

Special cases partial chunk handling in a different way, avoiding relying on a temporary Storage interface, and making it so that any proof over bits in the partial chunk always require only one digest of proof material.
Also renames the "hashes" field of Proof to "digests" which is more consistent with other usage of the term.

[storage/mmr/bitmap] Change how we handle partial chunks in proving

---

cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/ops.rs
cryptography/src/bls12381/primitives/variant.rs

Resolves: #977
- replace recursive bisection in partial verification with iterative loops
- expand test coverage for single signature and boundary cases

[cryptography/bls12381] Remove Bisection Recursion

---

Cargo.lock
Cargo.toml
broadcast/Cargo.toml
codec/Cargo.toml
consensus/Cargo.toml
cryptography/Cargo.toml
deployer/Cargo.toml
examples/bridge/Cargo.toml
examples/chat/Cargo.toml
examples/flood/Cargo.toml
examples/log/Cargo.toml
examples/vrf/Cargo.toml
macros/Cargo.toml
p2p/Cargo.toml
resolver/Cargo.toml
runtime/Cargo.toml
storage/Cargo.toml
stream/Cargo.toml
utils/Cargo.toml

```
.github/workflows/benchmark.yml                    |   28 +-
.github/workflows/coverage.yml                     |    6 +-
.github/workflows/tests.yml                        |   35 +-
Cargo.lock                                         |   52 +-
Cargo.toml                                         |   26 +-
broadcast/Cargo.toml                               |    2 +-
codec/Cargo.toml                                   |    2 +-
codec/src/types/bytes.rs                           |   13 +
codec/src/types/map.rs                             |   46 +
codec/src/types/net.rs                             |   64 +-
codec/src/types/primitives.rs                      |  118 +
codec/src/types/tuple.rs                           |   23 +
codec/src/types/vec.rs                             |   24 + …
```

[release] v0.0.51

---

cryptography/src/bls12381/benches/aggregate_verify_multiple_messages.rs
cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
cryptography/src/bls12381/benches/evaluate_point.rs
cryptography/src/bls12381/benches/partial_verify_multiple_public_keys.rs
cryptography/src/bls12381/benches/partial_verify_multiple_public_keys_precomputed.rs

Related: #988 
This is a stopgap to restore the benchmark CI (until we add self-hosted runners or refactor how tests are run).

[cryptography/benchmarks] Reduce Test Cardinality

---

runtime/src/utils/buffer/mod.rs

**Description:**  
This pull request corrects a typo in the test function name from `test_write_straddling_non_mergable` to `test_write_straddling_non_mergeable` in the `runtime/src/utils/buffer/mod.rs` file. No other logic or functionality was changed. This update improves code clarity and consistency in naming conventions.

Fix typo in test function name in mod.rs

---

deployer/src/ec2/aws.rs
deployer/src/ec2/destroy.rs

During the latest `alto` deploy, I ran into a number of flaky failures. After making this change, it was able to complete successfully:
```
2025-05-27T03:43:28.635747Z ERROR deployer: failed to create EC2 deployment error=AwsEc2(Unhandled(Unhandled { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })), connection: Unknown } }), meta: ErrorMetadata { code: None, message: None, extras: None } }))
```

[deployer] Perform Deletion Concurrently + Activate Automatic Retry

---

runtime/src/iouring/mod.rs

In `main`, the io_uring event loop `return`s immediately when the incoming work submission channel closes. This PR:
* Adds a `drain` function to process in-flight operations before returning
* Adds a config option to specify how long `drain` should wait for in-flight operations to complete before abandoning them

[runtime] Add iouring config for shutdown timeout

---

storage/src/mmr/benches/update.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/tests/mod.rs

Adds `add_batched` and `update_leaf_batched` methods to the mem-MMR which delays parent node digest updating until `sync` in order to avoid unnecessary digest recomputations (and ultimately parallelization).  Extends the leaf-updating benchmark to compare batching to no batching.

[storage/mmr/mem] add batch update feature to mem MMR

---

Cargo.lock
Cargo.toml
cryptography/Cargo.toml
cryptography/src/lib.rs
cryptography/src/sha256/mod.rs
stream/Cargo.toml
stream/src/lib.rs
stream/src/public_key/benches/receiver_receive.rs
stream/src/public_key/benches/sender_send.rs
stream/src/public_key/cipher.rs
stream/src/public_key/connection.rs
stream/src/public_key/mod.rs
stream/src/public_key/nonce.rs

Thanks to @dnkolegov-ar for finding these issues
Fixes #1013 
Fixes #1014 
Fixes #1016 
Updates the `ChaCha20Poly1305` cipher derivation for the `commonware-stream::public_key` module:
- Uses `hkdf` and `sha2::Sha256` to derive the cipher from the Diffie-Hellman  shared secret (rather than the shared secret directly)
- Includes a "commonware" constant, the application namespace, and the handshake transcript into the cipher derivation to tie the construction to the exact usecase
- Creates separate ciphers for each direction, allowing for simplification of the cipher nonce code

[stream] Harden KDF for ChaCha20Poly1305 cipher

---

consensus/src/simplex/actors/voter/actor.rs
consensus/src/threshold_simplex/actors/voter/actor.rs
runtime/src/utils/buffer/mod.rs
runtime/src/utils/buffer/read.rs
runtime/src/utils/buffer/write.rs
storage/src/archive/mod.rs
storage/src/journal/variable.rs

[storage/journal] Fix `journal::variable` Handling

---

storage/src/journal/fixed.rs

Allow fixed-item-length journal to recover from the situation where a blob is extended some number of bytes but a failure happens before all data is written into that extension. In this case, any items with bytes in the truncated section will produce checksum failures.
- This fix iteratively backs up over any such items until one with a valid checksum is found, or the newest blob is completely empty.
- A new test case simulates this situation and confirms recovery is successful.

[storage/journal/fixed] fix recovery bug in fixed-item-length journal

---

.github/workflows/tests.yml
runtime/src/network/iouring.rs
runtime/src/network/mod.rs

Should prevent `test_trait` from stalling and resolve #954. Also removes 1 line of dead code.

[runtime] enable force poll for iouring network tests

---

Cargo.lock
Cargo.toml
broadcast/Cargo.toml
codec/Cargo.toml
consensus/Cargo.toml
cryptography/Cargo.toml
deployer/Cargo.toml
examples/bridge/Cargo.toml
examples/chat/Cargo.toml
examples/flood/Cargo.toml
examples/log/Cargo.toml
examples/vrf/Cargo.toml
macros/Cargo.toml
p2p/Cargo.toml
resolver/Cargo.toml
runtime/Cargo.toml
storage/Cargo.toml
stream/Cargo.toml
utils/Cargo.toml

```
.github/workflows/coverage.yml                     |   3 -
.github/workflows/tests.yml                        |  10 +-
Cargo.lock                                         |  45 +-
Cargo.toml                                         |  25 +-
broadcast/Cargo.toml                               |   2 +-
broadcast/src/buffered/engine.rs                   |  47 +-
broadcast/src/buffered/ingress.rs                  |  45 +-
broadcast/src/buffered/mocks.rs                    |   6 +-
broadcast/src/buffered/mod.rs                      |  13 +-
codec/Cargo.toml                                   |   2 +-
codec/src/types/map.rs                             | 683 +++++++++++++++++----
codec/src/types/mod.rs                             |   1 +
codec/src/types/set.rs                             | 589 …
```

[release] v0.0.54

---

p2p/src/authenticated/actors/peer/actor.rs
p2p/src/authenticated/actors/peer/mod.rs

Logs the actual error instead of just `ChannelClosed`.

[p2p] log actual error instead of ChannelClosed

---

storage/src/mmr/benches/update.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/mem.rs

Instead of having the caller add leaf modifications one at a time, allow them to be provided in batch to allow for (later) parallelization of leaf digest computations.

[storage/mmr] change API for batching of leaf updates

---

storage/src/adb/any.rs
storage/src/adb/current.rs
storage/src/mmr/benches/append.rs
storage/src/mmr/benches/append_additional.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/benches/update.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/hasher.rs
storage/src/mmr/iterator.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/storage.rs
storage/src/mmr/tests/mod.rs
storage/src/mmr/verification.rs

- Make Standard<H> hasher own the internal cryptographic hasher. This will allow it to be easily cloned & used across multiple threads.
- Change Grafting<H> hasher to no longer require a reference to the base mmr as the source of grafted digests. Instead it's now the responsibility of the user to load the necessary grafted digests before using it.  This allows for concurrent retrieval of the grafted digests, and will allow for parallel computation of leaf digests without blocking on async calls.
- Remove async from leaf_digest(), clarifying it should never perform IO-bound computation to allow for CPU parallelization.
- Renames "chunk_pos" in Bitmap to the more terminologically accurate "chunk_num"

[storage/mmr] mmr::Hasher refactoring for parallel merklezation

---

Cargo.lock
runtime/src/utils/mod.rs
storage/Cargo.toml
storage/src/adb/any.rs
storage/src/adb/current.rs
storage/src/mmr/benches/update.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/hasher.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/tests/mod.rs

- Adds parallel version of mmr::mem::sync()
- Adds parallel version of mmr::mem::update_leaf_batched()
- Extends update benchmark to contrast performance of no-batching/serial batching/parallel batching
- Extends structures based on MMRs to accept an optional thread pool during initialization, which configures them for parallelizing batch operations.

[storage/mmr] Parallelize merkleization

---

storage/src/adb/any.rs
storage/src/adb/current.rs
storage/src/journal/fixed.rs
storage/src/metadata/mod.rs
storage/src/metadata/storage.rs
storage/src/mmr/journaled.rs

Adds destroy() capability to Metadata, mmr::Journaled, adb::Any, and adb::Current, and adds them to test cases creating each.

[storage] implement destroy for more storage classes

---

p2p/src/authenticated/actors/tracker/actor.rs
p2p/src/authenticated/actors/tracker/directory.rs
p2p/src/authenticated/actors/tracker/ingress.rs
p2p/src/authenticated/actors/tracker/reservation.rs

Fixes #1106 
Unfortunately I found it hard to create a test for this issue (to prevent regression) due to how the runtime deals with async stuff and how you have to release the reservation AFTER connecting, but also immediately, but then also during that time never loop a single time within the tracker actor

[p2p] Release sends message to `tracker` rather than `directory`

---

consensus/src/ordered_broadcast/config.rs
consensus/src/ordered_broadcast/engine.rs
consensus/src/ordered_broadcast/mod.rs
consensus/src/simplex/actors/voter/actor.rs
consensus/src/simplex/actors/voter/mod.rs
consensus/src/simplex/config.rs
consensus/src/simplex/engine.rs
consensus/src/simplex/mod.rs
consensus/src/threshold_simplex/actors/voter/actor.rs
consensus/src/threshold_simplex/actors/voter/mod.rs
consensus/src/threshold_simplex/config.rs
consensus/src/threshold_simplex/engine.rs
consensus/src/threshold_simplex/mod.rs
examples/bridge/src/bin/validator.rs
examples/log/src/main.rs
runtime/src/utils/buffer/read.rs
storage/src/adb/any.rs
storage/src/archive/benches/restart.rs
storage/src/archive/benches/utils.rs
storage/src/archive/mod.rs
storage/src/archive/storage.rs
storage/src/journal/benches/fixed_replay.rs
storage/src/journal/fixed.rs
storage/src/journal/variable.rs

- Changes fixed journal's replay functionality to guarantee in-order element production & optimizes it a bit.
- Changes adb::any's snapshot building to use replay now that it is ordered.
- Removes concurrency from variable journal's replay() so it produces elements in-order, though without any significant simplification or optimization.
- Removes replay_concurrency config parameters throughout.
Performance on the fixed_replay benchmark is about 25-30% faster.
Archive restart benchmark unaffected.
Addresses https://github.com/commonwarexyz/monorepo/issues/1109.

[storage/journal + storage/adb/any] Make replay ordered

---

storage/Cargo.toml
storage/src/adb/benches/any_init.rs
storage/src/adb/benches/anydb_init.rs
storage/src/adb/benches/bench.rs

The benchmark creates a large-ish random DB, closes it, then times how long it takes to re-open.

[storage/adb/any] add benchmark for adb::any startup

---

.github/workflows/fast.yml
Cargo.lock
Cargo.toml
stream/fuzz/Cargo.toml
stream/fuzz/fuzz_targets/connection.rs
stream/fuzz/fuzz_targets/handshake.rs
stream/fuzz/fuzz_targets/lazy_transport.rs
stream/fuzz/fuzz_targets/transport.rs
stream/src/public_key/handshake.rs
stream/src/public_key/mod.rs
stream/src/public_key/x25519.rs

This PR adds basic fuzz tests for `stream`.
`handshake` fuzzes the low-level primitive of the handshake protocol, which is why it requires some private handshake types.
Now I just made them public and also removed `cfg(test)` for x25519's `PublicKey::from_bytes`. I think you may have better ideas on how to implement that more correctly. If you do not want to make any changes to your type system, then we can remove the `handshake` test.

[stream] Add fuzz tests for handshake

---

storage/src/adb/any.rs
storage/src/adb/current.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/hasher.rs
storage/src/mmr/journaled.rs
storage/src/mmr/verification.rs

These functions never `await` anything. (In the old code, they `await`ed completion of function calls which are no longer `async` after this change.)

[storage] remove async from signatures of methods that don't need it

---

p2p/src/authenticated/discovery/actors/peer/actor.rs
p2p/src/authenticated/discovery/actors/peer/mod.rs
p2p/src/authenticated/lookup/actors/peer/actor.rs
p2p/src/authenticated/lookup/actors/peer/mod.rs

Related: #1133 
We should align the error (which already exists) with the metric name.

[p2p] Use existing `Error::InvalidChannel` + Assert on Invalid Message Sends

---

storage/src/adb/any.rs
storage/src/adb/current.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/hasher.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/mmr/mod.rs
storage/src/mmr/verification.rs

Having these functions potentially return Error is a holdover from when we had them "async" due to how grafting was previously implemented. This is no longer necessary, errors would have never been returned, since the only possible errors (MissingDigest/ExtraDigests) get captured and converted to verification failures (false).

[storage/mmr/verification.rs] remove Error being returned from proof verification functions

---

.github/actions/setup/action.yml
.github/workflows/fast.yml
.github/workflows/slow.yml
runtime/src/lib.rs
runtime/src/storage/audited.rs
runtime/src/storage/iouring.rs
runtime/src/storage/memory.rs
runtime/src/storage/metered.rs
runtime/src/storage/mod.rs
runtime/src/storage/tokio/fallback.rs
runtime/src/storage/tokio/mod.rs
runtime/src/storage/tokio/unix.rs
runtime/src/utils/buffer/mod.rs
runtime/src/utils/buffer/read.rs
runtime/src/utils/buffer/write.rs
storage/src/journal/fixed.rs
storage/src/journal/variable.rs
storage/src/metadata/mod.rs
storage/src/metadata/storage.rs
storage/src/mmr/journaled.rs
stream/fuzz/fuzz_targets/handshake.rs
stream/src/public_key/benches/sender_send.rs
utils/src/array/u64.rs
utils/src/bitvec.rs
utils/src/futures.rs
utils/src/time.rs

[runtime/storage] Optimize `unix` Performance + Consistent `resize` Behavior

---

stream/src/lib.rs
stream/src/public_key/cipher.rs
stream/src/public_key/connection.rs
stream/src/public_key/handshake.rs
stream/src/public_key/mod.rs
stream/src/public_key/nonce.rs
stream/src/public_key/x25519.rs

Fixes #1076 
Fixes #1018 by not letting a "spoofing" party keep the connection open longer than the handshake timeout (see https://github.com/commonwarexyz/monorepo/pull/1132#discussion_r2158034085)
TODO:

[stream] Add explicit key-confirmation to handshake

---

stream/fuzz/fuzz_targets/connection.rs

Related: #1132
The largest message we can send in the handshake is now larger (could include `KeyConfirmation`).

[stream] Fix fuzz/connection

---

p2p/src/authenticated/discovery/actors/dialer.rs
p2p/src/authenticated/discovery/actors/listener.rs
p2p/src/authenticated/lookup/actors/dialer.rs
p2p/src/authenticated/lookup/actors/listener.rs

Spans were added while benchmarking `examples::flood` but now are causing issues with tests. Removing until we actually need them (at which point we can review if this was even the right approach).

[p2p] Remove spans

---

storage/src/adb/any.rs
storage/src/adb/current.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/bitmap.rs
storage/src/mmr/hasher.rs
storage/src/mmr/journaled.rs
storage/src/mmr/verification.rs

- Allow an empty proof to authenticate an empty MMR.
- Simplify verification APIs by not requiring the user to provide the end element position, which can be derived from the starting position and the number of elements in the input.
- Perform more strict validation of the element range provided to verification (elements that fall outside of the MMR range result in error).

[storage/mmr] handle case of proving an MMR is empty

---

storage/src/metadata/benches/sync.rs
storage/src/metadata/benches/utils.rs
storage/src/metadata/mod.rs
storage/src/metadata/storage.rs

Modifying 1 key on a 100, 1000, and 10000 key store takes ~roughly the same time (and modifies the same amount of data on disk):
```
metadata::sync/keys=100 modified=1
time:   [3.3392 ms 3.4057 ms 3.4644 ms]
metadata::sync/keys=1000 modified=1
time:   [3.2514 ms 3.3059 ms 3.3589 ms]
metadata::sync/keys=10000 modified=1
time:   [3.2269 ms 3.5963 ms 3.8910 ms]
```

[storage/metadata] Improve Delta Write Efficiency for Common Case

---

stream/fuzz/fuzz_targets/handshake.rs
stream/src/lib.rs
stream/src/public_key/cipher.rs
stream/src/public_key/connection.rs
stream/src/public_key/handshake.rs
stream/src/public_key/mod.rs

Fixes #1178 
Technically only the first commit is needed, the other two clean up the code
Cleanup steps:
- Removed `create_handshake_transcript()` function which duplicates the logic of `commonware_utils::union`
- Removed `ListenerResponse` type and just use tuple instead. The codec already has default implementations for encoding/decoding tuples
- Change from `C: PublicKey` to `P: PublicKey` where appropriate to match the rest of the codebase
- Modified naming of handshake steps to be consistently 1) `Hello` and 2) `Confirmation`
- For MY hello or confirmation used variable names like `hello / confirmation`. For the OTHER's hello or confirmation, used variable names like `listener_*` or `dialer_*`
- When naming variables of the raw bytes, use `_msg` instead of `_bytes` for consistency …

[stream] Use full transcript in dialer key confirmation

---

consensus/src/ordered_broadcast/types.rs

Updated the error message for ChunkMismatch to be more specific and consistent with terminology.
Before: "Chunk mismatch from sender {0} with height {1}"
After: "Chunk payload mismatch from sequencer {0} at height {1}"

Improve error message for ChunkMismatch

---

Cargo.lock
Cargo.toml
broadcast/Cargo.toml
codec/Cargo.toml
codec/fuzz/Cargo.toml
coding/Cargo.toml
collector/Cargo.toml
consensus/Cargo.toml
cryptography/Cargo.toml
cryptography/fuzz/Cargo.toml
deployer/Cargo.toml
examples/bridge/Cargo.toml
examples/chat/Cargo.toml
examples/flood/Cargo.toml
examples/log/Cargo.toml
examples/sync/Cargo.toml
examples/vrf/Cargo.toml
macros/Cargo.toml
p2p/Cargo.toml
resolver/Cargo.toml
runtime/Cargo.toml
storage/Cargo.toml
storage/fuzz/Cargo.toml
stream/Cargo.toml
stream/fuzz/Cargo.toml
utils/Cargo.toml
utils/fuzz/Cargo.toml

```txt
.github/workflows/publish.yml                  |    5 +
.github/workflows/slow.yml                     |    4 +
Cargo.lock                                     |   85 +-
Cargo.toml                                     |   28 +-
README.md                                      |    1 +
broadcast/Cargo.toml                           |    2 +-
codec/Cargo.toml                               |    2 +-
codec/fuzz/Cargo.toml                          |    2 +-
coding/Cargo.toml                              |   31 +
coding/README.md                               |   10 +
coding/src/lib.rs                              |    8 +
coding/src/reed_solomon/benches/bench.rs       |    6 +
coding/src/reed_solomon/benches/decode.rs      |   54 +
coding/src/reed_solomon/benches/encode.rs      |   42 + …
```

[release] v0.0.56

---

storage/src/adb/any/mod.rs
storage/src/adb/any/sync/client.rs
storage/src/adb/any/sync/mod.rs
storage/src/adb/any/sync/resolver.rs
storage/src/journal/fixed.rs
storage/src/journal/mod.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mod.rs

This PR addresses #1213 by allowing for the re-use of existing persisted data when entering state sync.

[adb] [sync]  Re-use existing persisted data during state sync

---

storage/src/adb/any/sync/client.rs

Failing with:
```
thread 'adb::any::sync::client::tests::test_target_same_lower_bound' panicked at storage/src/adb/any/mod.rs:287:9:
assertion `left == right` failed
left: 111
right: 101
stack backtrace:
0: __rustc::rust_begin_unwind
at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
1: core::panicking::panic_fmt
at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
2: core::panicking::assert_failed_inner
3: core::panicking::assert_failed
at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:388:5
4: commonware_storage::adb::any::Any<E,K,V,H,T>::init_synced::{{closure}}
at ./src/adb/any/mod.rs:287:9
5: commonware_storage::adb::any::sync::client::Client<E,K,V,H,T,R>::step::{{closure}}
at …
```

[adb][sync] Target With Same Lower Bound

---

storage/src/adb/any/mod.rs
storage/src/adb/any/sync/client.rs
storage/src/mmr/journaled.rs

We weren't writing pinned nodes to the metadata, meaning that re-opening a synced database would fail if we didn't update/persist the metadata before closing the database.

[adb] [sync] Fix peristence bug causing checksum mismatch on synced database open

---

storage/src/adb/any/mod.rs
storage/src/adb/current.rs
storage/src/mmr/mem.rs
storage/src/mmr/mod.rs

Fixes issue where adb::Any was unnecessarily hashing database operations before putting them in the MMR, which does its own hashing of provided elements.

[storage/adb/any] remove double-hashing of elements

---

coding/fuzz/fuzz_targets/reed_solomon.rs
coding/src/reed_solomon/mod.rs
storage/fuzz/fuzz_targets/bmt_operations.rs
storage/src/bmt/benches/bench.rs
storage/src/bmt/benches/prove_range.rs
storage/src/bmt/benches/prove_single.rs
storage/src/bmt/mod.rs

Resolves: #1312 
> Why not just use an MMR?
* BMT is stupid simple to reason about (not to say MMR is "that" much harder 😉 ).
* The MMR contains additional logic to handle appends and historical proofs (not applicable to fixed-size datasets).
* MMR proof size varies based on the position being proven (BMTs are equal size).
TL; DR using an MMR would "probably be fine" but it just feels like the wrong tool for the job.

[storage/bmt] Add Range Proofs

---

storage/src/adb/immutable.rs
storage/src/adb/mod.rs

Adds pruning support to adb::immutable.
- Keys whose operation precedes the boundary will no longer be retrievable (requests will return None).
- Index is not lazily cleaned up, but will be cleaned on restart.

[storage/adb/immutable] pruning support

---

storage/src/adb/benches/bench.rs
storage/src/adb/benches/fixed_init.rs
storage/src/adb/benches/variable_init.rs

The benchmark follows the implementation of the any::Fixed init benchmark, only inserting varying sized vectors instead of fixed digests.
Because reads from the variable journal are not currently buffered, this benchmark runs slowly (3-7 seconds per iteration depending on the parameters).  It will allow us to measure the impact of buffering in https://github.com/commonwarexyz/monorepo/pull/1384

[storage/adb/any] create a new benchmark for the variable anydb

---

runtime/src/network/mod.rs

Without this, under the latest stable rust, we'd get the following CI failure under iouring build:
```
error: struct `Network` is never constructed
--> runtime/src/network/tokio.rs:161:12
|
161 | pub struct Network {
|            ^^^^^^^
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
```

[runtime] fix lint failure from updated rust due to unneeded module with iouring

---

storage/src/adb/any/variable/mod.rs
storage/src/adb/immutable/mod.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/store/mod.rs

Fixes 2 bugs:
1. All variable length stores were computing the wrong variable log rewind point during recovery in various cases.
2. Journaled MMR pop() wasn't re-adding the "extra" pinned nodes to the mem-mmr after resetting it, causing recovery to fail in some cases where the MMR had to be rewinded (since rewinding used pop()).
Improves the journal pop() test case to prevent regressions for (2), and immutable adb recery + non-adb store test cases to prevent regressions from (1) in those 2 stores.  Dan's new recovery test case(s) should prevent (1) from regressing in variable adb.

[storage/adb+mmr] Recovery bug fixes

---

storage/src/adb/any/variable/mod.rs
storage/src/adb/immutable/mod.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mem.rs
storage/src/store/mod.rs

This pull request refactors the recovery logic for operation logs in both variable and immutable database implementations, improving consistency and reliability after partial writes or crashes. It also enhances the Merkle Mountain Range (MMR) journaled implementation to better manage pinned nodes, ensuring proof validity and handling edge cases. Comprehensive new tests are added to verify correct recovery under various failure scenarios.
**Recovery logic improvements (most important):**
* Refactored the operation log recovery in `variable/mod.rs`, `immutable/mod.rs`, and `store/mod.rs` to track the first operation after the last commit point (`after_last_commit`) instead of relying on `end_loc` and `end_offset`, ensuring more precise rollback and pruning of uncommitted operations. …

[adb::variable::*] Fix Miscellaneous Recovery Issues

---

codec/src/error.rs

`codex::Error` in its current form does not allow the `thiserror::Error` proc macro to establish a source-chain. The `Display` impl generated by it will only emit the top level error and drop all underlying errors.
To allow it to establish a source chain the field needs to be either tagged `#[source]` or the field named `source: UnderlyingError`. (or tag it `[#from]`, but the very desirable `context` info does not allow for that)
I have opted to tag the field `#[source]` to mimimize churn. The `Source({1})` was also removed because the intended way to access the underlying information is via `std::error::Error::source`. And because having `Source({1})` would yield to duplicate messages both at error levels 0 and 1.

[codec] allow accessing error source chain

---

consensus/src/aggregation/engine.rs

Related: #1417 
Instead of waiting the full rebroadcast demo for verified but unconfirmed items, immediately mark for rebroadcast.

[consensus/aggregation] Improve Recovery Performance

---

storage/src/adb/keyless.rs
storage/src/store/operation.rs

Previously we were incorrectly putting offsets instead of values into the authenticated portion.  Moves the operation type from locations to the values journal so that proving works identically to other stores.

[storage/adb/keyless] fix authentication/proving in the keyless db

---

storage/src/adb/any/fixed/mod.rs
storage/src/adb/any/fixed/sync.rs
storage/src/adb/any/variable/mod.rs
storage/src/adb/current.rs
storage/src/adb/immutable/mod.rs
storage/src/adb/immutable/sync/mod.rs
storage/src/adb/keyless.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mod.rs
storage/src/mmr/verification.rs
storage/src/store/mod.rs
storage/src/store/operation.rs

- Adds "keyless get" (get_loc) to all stores, and makes get_metadata across all behave the same (returning commit position).
- More idiomatic naming in Operation for the key/value accessors/conversions.
- Improve behavioral and naming consistency between non-adb store and the others.
- Remove HistoricalProofSize errors and use precondition assertions instead (to be more consistent with other MMR code, which panics on incorrect usage rather than returning errors.)

[storage] add get_loc to all stores

---

storage/src/adb/any/fixed/sync.rs
storage/src/mmr/journaled.rs
storage/src/mmr/mod.rs

Implements a new method `init_from_pinned_nodes` that allows for creation of a new journaled MMR from the pinned nodes corresponding to a given MMR, along with the size of that MMR.
Resolves #1421

[mmr] Add `init_from_pinned_nodes`

---

storage/src/mmr/verification.rs

For efficient stream processing, it can be useful to send some subset of a range (i.e block events) to a consumer. While it would be possible to send a range proof over the same range (and only send digests for items the receiver doesn't care about), it won't be as efficient.
Abandoned direction: #1469

[storage/adb] Support Multi-Proofs

---

runtime/src/utils/buffer/pool.rs

Tiny optimizaiton: use atomic int fetch_add w/ relaxed ordering to avoid locking when assigning unique IDs.

[runtime/util/buffer] use fetch_add instead of write lock for unique id assignment

---

runtime/src/iouring/mod.rs
runtime/src/network/iouring.rs
runtime/src/storage/iouring.rs
runtime/src/tokio/runtime.rs

While reviewing the iouring code I asked myself why single issuer mode wasn't being used. Then realized there's already an issue for it.
This PR also enables defer task run when single issuer is enabled. This is recommended by the kernel docs and safe to do in our case due to the way the loop is structured.
From https://man7.org/linux/man-pages/man3/io_uring_submit_and_wait.3.html
> Ideally used with a ring setup with IORING_SETUP_SINGLE_ISSUER|IORING_SETUP_DEFER_TASKRUN as that will greatly reduce the number of context switches that an application will see waiting on multiple requests.
Fixes https://github.com/commonwarexyz/monorepo/issues/1037.

[runtime/{network,storage}] enable iouring single issuer and defer task run

---

runtime/src/process/metered.rs

The test was failing intermittently when run in parallel with other tests because RSS is affected by memory allocations/deallocations from concurrent tests.
Added retry logic using `catch_unwind` to handle transient failures, the test now retries up to 10 times before failing, which in my testing allowed it to succeed consistently.
Probably not triggered in CI due to not enough parallelization (my desktop has 32 cores). It's a bit of a dirty solution, but I don't know what else can be done.

[runtime] fix flaky process metrics test

---

storage/fuzz/fuzz_targets/journal_operations.rs
storage/src/adb/any/fixed/mod.rs
storage/src/adb/any/fixed/sync.rs
storage/src/adb/any/variable/mod.rs
storage/src/adb/immutable/mod.rs
storage/src/adb/keyless.rs
storage/src/freezer/storage.rs
storage/src/journal/fixed.rs
storage/src/journal/variable.rs
storage/src/mmr/journaled.rs
storage/src/store/mod.rs

(1) We were incorrectly assuming journal rewind() and mmr.pop() were "sticky" operations, but in fact they aren't sticky until sync is called. This PR makes pop() sticky, and calls sync() where appropriate after rewinding.
(2) The journaled MMR's sync() operation was returning immediately when size == 0, which was preventing the syncing of a rewind to offset 0. Removed the size == 0 check, and added a regression test for this scenario.
Rewind documentation is updated to clearly state its properties.

[storage] fix rewind bugs

---

AGENTS.md
Cargo.lock
cryptography/src/blake3/mod.rs
cryptography/src/bls12381/dkg/dealer.rs
cryptography/src/bls12381/dkg/ops.rs
cryptography/src/bls12381/primitives/group.rs
cryptography/src/bls12381/primitives/ops.rs
cryptography/src/bls12381/primitives/poly.rs
cryptography/src/bls12381/primitives/variant.rs
cryptography/src/bls12381/scheme.rs
cryptography/src/bls12381/tle.rs
cryptography/src/ed25519/scheme.rs
cryptography/src/lib.rs
cryptography/src/secp256r1/scheme.rs
cryptography/src/sha256/mod.rs
examples/vrf/Cargo.toml
examples/vrf/src/handlers/contributor.rs

Closes #1088.
This also modifies things to avoid the use of `Rng`, preferring `RngCore` instead (just within this crate), and the use of `RngCore + CryptoRng` to instead use `CryptoRngCore`.

[cryptography] Use CryptoRng consistently

---

storage/src/adb/benches/bench.rs
storage/src/adb/benches/fixed_generate.rs
storage/src/adb/benches/keyless_generate.rs
storage/src/adb/benches/variable_generate.rs

Adds benchmarks for generating adb::fixed, adb::variable, and adb::keyless databases with small # of updates between commits.

[storage/adb/bench] benchmarks for generating various adbs

---

storage/src/adb/any/variable/mod.rs
storage/src/adb/any/variable/sync.rs
storage/src/adb/immutable/mod.rs
storage/src/adb/keyless.rs
storage/src/archive/prunable/storage.rs
storage/src/cache/storage.rs
storage/src/freezer/storage.rs
storage/src/journal/fixed.rs
storage/src/journal/mod.rs
storage/src/journal/variable.rs
storage/src/store/mod.rs
storage/src/store/operation.rs

Our journals respond rather unpredictably when requesting non-existent items. For example, depending on the specific input values, the variable journal might return either None or one of a variety of error types. The fixed journal might return ItemPruned, or instead simply panic if the requested item is out of range.
This PR makes journal reads of non-existent items consistently return either:
- [Section|Item]Pruned, if the requested item/section has been pruned, or
- [Section|Item]OutOfRange, if the requested item/section does not exist.
The only exception is an invalid variable journal section offset, which we clarify will result in error, but the exact type is undefined.
In no circumstances will a request for a non-existent item return "None".

[storage/journal] improve consistency in journal read/get error handling

---

utils/src/futures.rs

Allows an application to employ a pattern like this:
```
_ = response.closed() => {
// The response was cancelled
warn!(view, "verify aborted");
}
```
To give up early on some work (if there is no need to send data anymore).

[utils] Add `Closed` Helper

---

resolver/src/p2p/wire.rs

Eliminates redundant clone() call in test_codec_response() since the  encoded variable is not used after Message::decode().

Remove unnecessary clone() in wire message test

---

runtime/src/deterministic.rs

Iterate over pending tasks once (rather than twice)

[runtime/deterministic] Cleanup `.clear()`

---

.github/workflows/coverage.yml
.github/workflows/fast.yml
.github/workflows/slow.yml
cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
storage/src/adb/benches/current_init.rs
storage/src/adb/benches/fixed_generate.rs
storage/src/adb/benches/fixed_init.rs
storage/src/adb/benches/keyless_generate.rs
storage/src/adb/benches/variable_generate.rs
storage/src/adb/benches/variable_init.rs

Switches CI's test runner over to `cargo-nextest`.
For the `Fast` tests ([`nextest` w/ 2 partitions](https://github.com/commonwarexyz/monorepo/actions/runs/17742610001/job/50420087520) vs. [`cargo test`](https://github.com/commonwarexyz/monorepo/actions/runs/17742291236/job/50419045877)), shaves:
*  `3m47s` off of the `ubuntu-latest` tests
* `6m35s` off of the `windows-latest` tests
* `3m31s` off of the `macos-latest` tests 
For the `Slow` tests ([`nextest` w/ 4 partitions](https://github.com/commonwarexyz/monorepo/actions/runs/17742610001/job/50420087520) vs. [`cargo test`](https://github.com/commonwarexyz/monorepo/actions/runs/17722980678/job/50358490051)), shaves:
* `31m49s` off of the `ubuntu-latest` tests
* `31m56s` off of the `windows-latest` tests
* `36m5s` off of the …

[ci] Use `cargo-nextest` for `Fast`/`Slow` Tests

---

.github/workflows/fast.yml

Small cleanup to CI - uses `taiki-e/install-action` rather than manually installing and caching binaries from the `crates.io` registry.
_note_: `cargo-fuzz` is still built manually + cached, since it only distributes an `x86_64-unknown-linux-musl` binary (https://github.com/rust-fuzz/cargo-fuzz/releases/tag/0.12.0). We could use this with the existing runner, but would need to adjust the fuzz tests to also run with `musl` rather than `libc`; doesn't seem very desirable imo.
closes #1612

[ci] Use `taiki-e/install-action`

---

storage/src/adb/benches/current_init.rs
storage/src/adb/benches/fixed_init.rs
storage/src/adb/benches/variable_init.rs
storage/src/index/benches/hashmap_insert.rs
storage/src/index/benches/hashmap_insert_fixed.rs
storage/src/index/benches/hashmap_iteration.rs
storage/src/index/benches/insert.rs
storage/src/mmr/benches/append.rs
storage/src/mmr/benches/append_additional.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/benches/update.rs
storage/src/store/benches/restart.rs

Requested by @patrick-ogrady, tunes down the `commonware-storage` benchmarks when running in test mode.

[storage] Tune benchmarks down in CI tests

---

consensus/src/marshal/actor.rs
consensus/src/marshal/config.rs
consensus/src/marshal/ingress/mod.rs
consensus/src/marshal/mod.rs
consensus/src/marshal/resolver/mod.rs
consensus/src/marshal/resolver/p2p.rs

Allows for a generic [`Resolver`](https://docs.rs/commonware-resolver/latest/commonware_resolver/trait.Resolver.html) to be used in [`marshal::Actor`](https://docs.rs/commonware-consensus/latest/commonware_consensus/marshal/actor/struct.Actor.html), rather than requiring the use of the `p2p` variant.
Fixes #1329

[consensus/marshal] Allow generic `Resolver`

---

storage/src/mmr/bitmap.rs
storage/src/mmr/proof.rs

Small update of the size field documentation to clarify that authenticated data structures other than a pure MMR may override its precise meaning.

[storage/mmr] update comment for 'size' field of Proof

---

runtime/src/iouring/mod.rs
runtime/src/network/iouring.rs
runtime/src/tokio/runtime.rs

With `force_poll` set to `None` the io_uring event loop could park forever if the submission channel closed after we had already entered `submit_and_wait`. Since a channel drop doesn't emit a completion queue event, the loop never resumed, so shutdown was never triggered. This PR makes the `force_poll` interval mandatory, so we always return to user space periodically, and therefore periodically check whether the submission channel is still open. The flaky test now deliberately keeps the channel alive long enough to reproduce the old race (this triggered the original issue consistently).
Fix #1691.

[runtime/io_uring] make force_poll mandatory

---

coding/src/benches/bench.rs
stream/fuzz/fuzz_targets/e2e.rs

`clippy 0.1.88` complains about not putting values inside the `{}`.
More [recent](https://github.com/rust-lang/rust-clippy/issues/15516) clippy versions don't complain about this by default, so I'm not sure if we care to enforce this or not. At the least, this PR makes the code more similar to other `println!` usages.

fix clippy warnings on println formatting

---

storage/src/adb/any/fixed/mod.rs
storage/src/adb/any/variable/mod.rs
storage/src/adb/verify.rs
storage/src/mmr/journaled.rs
storage/src/mmr/proof.rs
storage/src/mmr/verification.rs

Change max_ops in proof generation in adb::variable to NonZeroU64 to match the other adb proving APIs and prevent generation of an unverifiable empty proof, and disallow proofs over empty ranges / element lists more broadly.
Multi_proving over empty element lists was special cased to have an empty list of digests but non-zero size for non-empty databases, whereas empty range proofs would include the digests of every MMR peak (allowing root reconstruction if it were to be handled properly).  Neither approach is particuarly appealing, and it feels better to simply require you always be proving inclusion of *something*.
Tweaked and added a few more tests around empty proof verification. Empty proofs should only verify against a completely empty mmr and nothing else.

[storage/mmr] change anydb::variable max_ops to NonZeroU64

---

coding/fuzz/src/lib.rs
coding/src/benches/bench.rs
coding/src/benches/bench_size.rs
coding/src/lib.rs
coding/src/no_coding.rs
coding/src/reed_solomon/mod.rs

- Adds in the affordances for ZODA
- An index is always passed, making sure that verifiers are in control of this information
- A `check` step is added, producing one checked shard (your own), checking data for future reshards, and the reshard you need to send to others.

Add more adjustments to the generic coding API

---

storage/src/adb/any/fixed/mod.rs
storage/src/adb/any/variable/mod.rs
storage/src/adb/current.rs
storage/src/adb/immutable/mod.rs
storage/src/mmr/location.rs
storage/src/mmr/position.rs

* Use `saturating_add` instead of `checked_add` to prevent panics on too-large input
* Add documentation to clarify that `Location` and `Position` operations panic on underflow/overflow
Resolves #1749

[storage] Add `Location`/`Position` documentation; prevent panics

---

consensus/src/simplex/mod.rs
consensus/src/threshold_simplex/mod.rs
p2p/src/simulated/network.rs
storage/src/adb/any/fixed/sync.rs

Drop all instances of `context.clone().with_label()`.

[consensus, p2p, storage] remove superfluous context cloning

---

consensus/src/simplex/engine.rs
consensus/src/threshold_simplex/engine.rs
p2p/src/authenticated/discovery/actors/dialer.rs
p2p/src/authenticated/discovery/actors/listener.rs
p2p/src/authenticated/lookup/actors/dialer.rs
p2p/src/authenticated/lookup/actors/listener.rs
runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/tokio/runtime.rs

1. Fix `spawn_ref` implementations to set the child list before returning the closure (same as is done on `spawn`).
2. Extend runtime child-task tests to exercise both `spawn` and `spawn_ref` (these changes catch the issue fixed above).
3. Update all actors that were doing `context.clone().spawn()` on start, to use `spawn_ref` instead.

[runtime] Fix spawn_ref child tracking and adopt it across long-lived actors

---

p2p/src/authenticated/discovery/mod.rs
p2p/src/authenticated/lookup/mod.rs
runtime/src/deterministic.rs
runtime/src/lib.rs
runtime/src/tokio/mod.rs
runtime/src/tokio/runtime.rs
runtime/src/utils/handle.rs
runtime/src/utils/mod.rs

Precursor: #1784 
It turns out that `catch_panic` on `tokio` was ~useless. This change standardizes panic handling between tokio/deterministic and adds tests to ensure a panic in some observed task bubbles up.
This is often the intended behavior for a blockchain node (where a panic internally can cause a halt) but isn't necessarily intended for all applications (and thus the setting to catch_panics is retained).

[runtime] Standardize Panic Handling

---

.github/workflows/benchmark.yml
cryptography/Cargo.toml
cryptography/src/bls12381/benches/dkg_recovery.rs
cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
storage/Cargo.toml
storage/src/index/benches/hashmap_insert.rs
storage/src/index/benches/hashmap_insert_fixed.rs
storage/src/index/benches/hashmap_iteration.rs
storage/src/index/benches/insert.rs
storage/src/mmr/benches/append.rs
storage/src/mmr/benches/append_additional.rs
storage/src/mmr/benches/prove_many_elements.rs
storage/src/mmr/benches/prove_single_element.rs
storage/src/mmr/benches/update.rs

Some benchmarks are currently parameterized to run less iterations in "test mode." Because commonware doesn't use [integration benchmarks](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests), rustc still links `libtest` even without the presence of a harness, enabling `cfg(test)`.
This changes adds a new `cfg` flag to `commonware-cryptography` and `commonware-storage`, making this toggle explicit.
fixes https://github.com/commonwarexyz/monorepo/issues/1807

[ci] Run all benchmarks in `benchmarks` job

---

storage/src/adb/any/fixed/mod.rs
storage/src/adb/any/fixed/sync.rs
storage/src/adb/current.rs

- Implement floor raising policy described in https://github.com/commonwarexyz/monorepo/issues/1805 for adb::fixed::any and adb::current.
- Makes adb::current treat the last commit operation only as "active". This allows proving an adb::current is empty, which is important for exclusion proofs.
- Changes how the status bitmap is updated during replay. Instead of passing into adb::any (requiring the adb::any understand how bitmaps work), the adb::current instead passes in a closure that is invoked for each replayed operation.
Porting the policy to the remaining stores will be done in a separate PR.

[storage/adb] Implement new floor raising policy in adb::fixed::any
