commonwarexyz/monorepo

- docs/index.html
This pull request includes changes to the `docs/index.html` file. The changes primarily revolve around modifying the CSS properties for certain elements to adjust the layout and design of the web page.
The most notable changes are:
* [`docs/index.html`](diffhunk://#diff-b04b38d4e36f7a7171aeb211bf933eaf36d41d9866ebbc3639f673f84dc350aeL52-R57): The `font-size` property for the main container has been reduced from `1.3em` to `1em`, and the `font-size` for the `.logo-line` class has been reduced from `1.4em` to `1.2em`. The `white-space` property has been removed from the `.vertical-logo-symbol`, `.horizontal-logo-symbol`, and `.edge-logo-symbol` classes and added to the `.logo-line` class.
> [docs] reduce font size

- .github/workflows/crates.yml
- .github/workflows/rust.yml
- examples/chat/README.md
- examples/chat/src/main.rs
* `tokio` performs much better in `release`
> [examples/chat] run as `release`

- Cargo.lock
- examples/chat/Cargo.toml
- examples/chat/src/main.rs
- p2p/Cargo.toml
- p2p/src/config.rs
- p2p/src/lib.rs
* Rename `Config::default` to `Config::recommended`
* Introduce `Config::aggressive` to minimize peer discovery time on local demos
> [p2p] `Config::aggressive` for Local Demos

- Cargo.lock
- examples/chat/Cargo.toml
- examples/chat/README.md
- examples/chat/src/main.rs
- p2p/src/channels.rs
> [examples/chat] Add Documentation for `Offline Friends`

- p2p/src/lib.rs
* Improve Encryption documentation
> [p2p] Elaborate on `u64` vs `u80/u88`

- .github/workflows/rust.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- cryptography/Cargo.toml
- cryptography/src/bls12381/benches/dkg_recovery.rs
- cryptography/src/bls12381/benches/reshare_recovery.rs
- cryptography/src/bls12381/dkg/contributor.rs
- cryptography/src/bls12381/dkg/mod.rs
- cryptography/src/bls12381/scheme.rs
- cryptography/src/ed25519.rs
- examples/chat/Cargo.toml
- examples/chat/src/handler.rs
- examples/chat/src/logger.rs
- examples/chat/src/main.rs
- examples/vrf/Cargo.toml
- examples/vrf/src/main.rs
- p2p/Cargo.toml
- p2p/src/actors/router/actor.rs
- p2p/src/actors/router/ingress.rs
- p2p/src/actors/tracker/actor.rs
- p2p/src/channels.rs
- p2p/src/config.rs
- p2p/src/lib.rs
> [p2p] E2E Connectivity Test + Return Send Success

- .github/workflows/coverage.yml
- codecov.yml
- p2p/src/connection/handshake.rs
- p2p/src/connection/stream.rs
(a useful excuse to test new coverage CI)
> [p2p] Make `create_handshake` sync + Test Handshake Create/Verify

- .github/workflows/publish.yml
- Cargo.lock
- Cargo.toml
- README.md
- cryptography/Cargo.toml
- cryptography/src/lib.rs
- docs/index.html
- examples/chat/Cargo.toml
- examples/vrf/Cargo.toml
- p2p/Cargo.toml
- p2p/src/authenticated/mod.rs
- p2p/src/authenticated/network.rs
- p2p/src/lib.rs
- p2p/src/simulated/mod.rs
- p2p/src/simulated/network.rs
- runtime/Cargo.toml
- runtime/README.md
- runtime/src/deterministic.rs
- runtime/src/lib.rs
- runtime/src/tokio.rs
- runtime/src/utils.rs
* Provides an abstract `p2p` layer that can be tuned to mimic real-world network topologies. 
* Introduce `runtime` to make this abstract `p2p` layer deterministic/replayable. (#63)
> [p2p] Implement `Simulated`

- Cargo.lock
- examples/chat/Cargo.toml
Resolves: https://rustsec.org/advisories/RUSTSEC-2024-0019.html
> [chat] Update `crossterm`

- p2p/src/authenticated/actors/peer/ingress.rs
- p2p/src/authenticated/connection/handshake.rs
- p2p/src/authenticated/connection/instance.rs
- p2p/src/authenticated/connection/x25519.rs
- p2p/src/simulated/mod.rs
- p2p/src/simulated/network.rs
- runtime/src/lib.rs
- runtime/src/mocks.rs
> [p2p] Better test `authenticated` and `simulated`

- Cargo.lock
- examples/chat/src/main.rs
- p2p/src/authenticated/actors/peer/ingress.rs
- p2p/src/authenticated/actors/router/ingress.rs
- p2p/src/authenticated/actors/tracker/actor.rs
- p2p/src/authenticated/channels.rs
- p2p/src/authenticated/connection/handshake.rs
- p2p/src/authenticated/connection/instance.rs
- p2p/src/authenticated/mod.rs
- p2p/src/simulated/mod.rs
- runtime/Cargo.toml
- runtime/src/deterministic.rs
- runtime/src/lib.rs
> [runtime/deterministic]: Add Metrics

- CONTRIBUTING.md
- LICENSE-APACHE
- README.md
Set expectations for external contributors that want to work on the Commonware Library.
> [docs] Contributing Guidelines

- examples/chat/README.md
- examples/chat/src/main.rs
- p2p/src/authenticated/mod.rs
> [Docs] Add synchronization assumption

- codecov.yml
- p2p/src/simulated/mod.rs
- p2p/src/simulated/network.rs
> [p2p/simulated] Add multiplexing

- Cargo.lock
- Cargo.toml
- cryptography/Cargo.toml
- examples/chat/Cargo.toml
- examples/vrf/Cargo.toml
- p2p/Cargo.toml
- runtime/Cargo.toml
This pull request includes version updates for several dependencies across multiple `Cargo.toml` files in the project. The main changes involve incrementing the versions of the `commonware` packages to ensure compatibility and improvements.
Dependency version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L12-R14): Updated versions for `commonware-cryptography` to `0.0.9`, `commonware-runtime` to `0.0.6`, and `commonware-p2p` to `0.0.20`.
* [`cryptography/Cargo.toml`](diffhunk://#diff-939918f71e6979dfb52d74cb04f30452ba12e40e04afa38a7b43c09bfd33f60dL5-R5): Updated `commonware-cryptography` version to `0.0.9`.
* [`examples/chat/Cargo.toml`](diffhunk://#diff-a3ad88990350c3c7832d4772385482bd7cf9ce312385fc96e972dfdcb669073cL5-R5): …
> [release] 10/8/24

- p2p/src/authenticated/actors/peer/ingress.rs
- p2p/src/authenticated/actors/router/actor.rs
- p2p/src/authenticated/actors/router/ingress.rs
- p2p/src/authenticated/channels.rs
- p2p/src/authenticated/metrics.rs
- p2p/src/authenticated/mod.rs
- p2p/src/authenticated/network.rs
- p2p/src/lib.rs
- p2p/src/simulated/ingress.rs
- p2p/src/simulated/metrics.rs
- p2p/src/simulated/mod.rs
- p2p/src/simulated/network.rs
> [p2p/simulated] Allow peers/links to be added/removed at any time

- consensus/src/fixed/config.rs
- consensus/src/fixed/engine.rs
- consensus/src/fixed/mod.rs
- consensus/src/fixed/orchestrator.rs
- consensus/src/fixed/wire.proto
Fetching wasn't fast enough to keep up with consensus. Now it is.
> [consensus] Send batched backfill requests

- Cargo.lock
- Cargo.toml
- cryptography/Cargo.toml
- examples/chat/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- runtime/Cargo.toml
- utils/Cargo.toml
This pull request updates the version numbers for several dependencies and examples in the `Cargo.toml` files to ensure compatibility and include the latest improvements. The most important changes include version updates for `commonware` dependencies and example projects.
Dependency version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L14-R18): Updated versions for `commonware-cryptography`, `commonware-macros`, `commonware-p2p`, `commonware-runtime`, and `commonware-utils` dependencies.
Example projects version updates:
* [`cryptography/Cargo.toml`](diffhunk://#diff-939918f71e6979dfb52d74cb04f30452ba12e40e04afa38a7b43c09bfd33f60dL5-R5): Updated version for `commonware-cryptography` to `0.0.10`.
* …
> [release] 10/11/14

- p2p/src/authenticated/metrics.rs
- p2p/src/authenticated/network.rs
- p2p/src/simulated/metrics.rs
- runtime/src/deterministic.rs
- utils/src/lib.rs
> [nits] extract unrelated changes from `commonware-consensus`

- Cargo.lock
- Cargo.toml
- cryptography/Cargo.toml
- examples/chat/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- runtime/Cargo.toml
- utils/Cargo.toml
This pull request updates the version numbers for several dependencies in the `Cargo.toml` files across multiple modules in the project. These changes ensure that the project uses the latest versions of its dependencies.
Dependency version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R20): Updated versions for `commonware-cryptography`, `commonware-macros`, `commonware-p2p`, `commonware-runtime`, and `commonware-utils`.
* [`cryptography/Cargo.toml`](diffhunk://#diff-939918f71e6979dfb52d74cb04f30452ba12e40e04afa38a7b43c09bfd33f60dL5-R5): Updated `commonware-cryptography` version to `0.0.11`.
* [`examples/chat/Cargo.toml`](diffhunk://#diff-a3ad88990350c3c7832d4772385482bd7cf9ce312385fc96e972dfdcb669073cL5-R5): Updated …
> [release] 10/30/24

- Cargo.lock
- Cargo.toml
- cryptography/Cargo.toml
- examples/chat/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- macros/src/lib.rs
- p2p/Cargo.toml
- runtime/Cargo.toml
- storage/Cargo.toml
- utils/Cargo.toml
This pull request includes several version updates for various dependencies and a documentation improvement. The most important changes include updating the versions of multiple `commonware` crates and adding details to the documentation for the `macros::select!` implementation.
Dependency version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R20): Updated versions for `commonware-cryptography`, `commonware-macros`, `commonware-p2p`, `commonware-runtime`, `commonware-storage`, and `commonware-utils`.
* [`cryptography/Cargo.toml`](diffhunk://#diff-939918f71e6979dfb52d74cb04f30452ba12e40e04afa38a7b43c09bfd33f60dL5-R5): Updated version from `0.0.11` to `0.0.12`.
* [`examples/chat/Cargo.toml`](diffhunk://#diff-a3ad88990350c3c7832 …
> [release] 11/5/24

- storage/src/archive/mod.rs
> [storage/archive] Diagram typo

- docs/blogs/commonware-cryptography.html
- docs/blogs/commonware-runtime.html
- docs/blogs/introducing-commonware.html
- docs/index.html
Read more: https://www.cloudflare.com/web-analytics/
> [website] Add Cloudflare Analytics

- examples/chat/src/main.rs
- examples/vrf/src/main.rs
- p2p/src/authenticated/actors/listener.rs
- p2p/src/authenticated/actors/tracker/actor.rs
- p2p/src/authenticated/actors/tracker/mod.rs
- p2p/src/authenticated/config.rs
- p2p/src/authenticated/connection/handshake.rs
- p2p/src/authenticated/connection/instance.rs
- p2p/src/authenticated/connection/mod.rs
- p2p/src/authenticated/mod.rs
- p2p/src/authenticated/network.rs
> [p2p] Add `namespace` to required configuration

- stream/src/placeholder/instance.rs
- stream/src/placeholder/mod.rs
- stream/src/placeholder/utils/nonce.rs
> [stream] Refactor nonce

- .github/workflows/tests.yml
- stream/src/public_key/utils/nonce.rs
https://doc.rust-lang.org/stable/clippy/continuous_integration/github_actions.html
closes https://github.com/commonwarexyz/monorepo/issues/207
> [workflow] Linting: Add all targets/features to clippy lint

- cryptography/src/lib.rs
> [cryptography] `Sync` hasher

- p2p/src/authenticated/actors/dialer.rs
- p2p/src/authenticated/actors/listener.rs
- p2p/src/authenticated/actors/peer/actor.rs
- p2p/src/authenticated/actors/peer/mod.rs
- p2p/src/authenticated/actors/spawner/ingress.rs
- stream/src/lib.rs
- stream/src/public_key/connection.rs
- stream/src/public_key/handshake.rs
- stream/src/public_key/mod.rs
- stream/src/public_key/utils/codec.rs
- stream/src/public_key/utils/nonce.rs
- stream/src/public_key/x25519.rs
> [stream] Cleanup Public Interface: `Error` type, `send/receive` traits, rename `Instance` to `Connection`

- p2p/src/utils/requester.rs
- runtime/src/lib.rs
> [p2p/requester] Track Outstanding Requests + Add `handle`

- Cargo.lock
- Cargo.toml
- README.md
- cryptography/Cargo.toml
- docs/index.html
- examples/chat/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- runtime/Cargo.toml
- storage/Cargo.toml
- stream/Cargo.toml
- utils/Cargo.toml
Resolves: #187 
Release `commonware-stream` and add it to the `README`/`website`.
> [release] 12/9/24

- .github/actions/setup/action.yml
- .github/workflows/publish.yml
> [CI] Publish Stream

- Cargo.lock
- stream/Cargo.toml
- stream/src/public_key/benches/connection.rs
- stream/src/public_key/connection.rs
- stream/src/public_key/mod.rs
> [stream/public_key] Add benchmarks for `connection`

- consensus/src/simplex/actors/voter/actor.rs
- consensus/src/simplex/mocks/conflicter.rs
- consensus/src/simplex/mocks/nuller.rs
- consensus/src/simplex/prover.rs
- consensus/src/simplex/verifier.rs
- cryptography/src/bls12381/benches/partial_signature_aggregation.rs
- cryptography/src/bls12381/benches/signature_aggregation.rs
- cryptography/src/bls12381/benches/signature_generation.rs
- cryptography/src/bls12381/benches/signature_verification.rs
- cryptography/src/bls12381/benches/signature_verify_aggregation.rs
- cryptography/src/bls12381/mod.rs
- cryptography/src/bls12381/primitives/mod.rs
- cryptography/src/bls12381/primitives/ops.rs
- cryptography/src/bls12381/scheme.rs
- cryptography/src/ed25519.rs
- cryptography/src/lib.rs
- examples/vrf/src/handlers/arbiter.rs
- examples/vrf/src/handlers/contributor.rs
- examples/vrf/src/handlers/vrf.rs
- p2p/src/authenticated/actors/tracker/actor.rs
- stream/src/public_key/handshake.rs
- utils/src/lib.rs
> [cryptography/ed25519] add rfc8032 test vectors for ed25519

- .github/workflows/benchmark.yml
Related: #286 
Make it possible to manually trigger a benchmark run.
> [CI] Add `workflow_dispatch` Option

- p2p/src/authenticated/actors/peer/actor.rs
This `where` doesn't appear to be used
> remove unused `where` keyword

- cryptography/src/ed25519.rs
- cryptography/src/lib.rs
Closes #297 
This adds basic Batch Verification support for Ed25519.
> [cryptography/ed25519]: add Ed25519 batch_verify function

- .github/workflows/benchmark.yml
Fixes #322 
Seems to work! https://github.com/commonwarexyz/benchmarks/commit/a74a17c2ab07007392704eea63d2c8e20bdd71bb
> Publish benchmarks to root folder

- cryptography/src/bls12381/scheme.rs
- cryptography/src/ed25519/scheme.rs
- cryptography/src/lib.rs
- cryptography/src/secp256r1.rs
> [cryptography] add default implementation for `Scheme::from_seed` fn

- Cargo.lock
- consensus/src/lib.rs
- consensus/src/simplex/actors/resolver/actor.rs
- consensus/src/simplex/actors/voter/actor.rs
- consensus/src/simplex/actors/voter/mod.rs
- consensus/src/simplex/config.rs
- consensus/src/simplex/engine.rs
- consensus/src/simplex/mocks/supervisor.rs
- consensus/src/simplex/mod.rs
- cryptography/src/bls12381/benches/dkg_recovery.rs
- cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
- cryptography/src/bls12381/benches/threshold_signature_recover.rs
- cryptography/src/bls12381/dkg/dealer.rs
- cryptography/src/bls12381/dkg/mod.rs
- cryptography/src/bls12381/dkg/ops.rs
- cryptography/src/bls12381/mod.rs
- cryptography/src/bls12381/primitives/mod.rs
- cryptography/src/bls12381/primitives/ops.rs
- cryptography/src/bls12381/primitives/poly.rs
- examples/log/src/application/supervisor.rs
- examples/vrf/src/handlers/contributor.rs
- examples/vrf/src/handlers/vrf.rs
- runtime/src/mocks.rs
- utils/Cargo.toml
- utils/src/lib.rs
Related: #336 
This pull request includes significant changes to the consensus module, focusing on simplifying the `Supervisor` trait and improving the handling of tasks within the resolver actor. Additionally, it introduces the use of a seeded RNG in cryptographic benchmarks. Below are the most important changes:
* Removed the `Seed` type from the `Supervisor` trait and updated the `leader` method to no longer require a seed parameter. (`consensus/src/lib.rs`, `consensus/src/simplex/mocks/supervisor.rs`, `consensus/src/simplex/actors/voter/actor.rs`, `consensus/src/simplex/config.rs`, `consensus/src/simplex/engine.rs`) [[1]](diffhunk://#diff-a27358d97e0527c88e76e3cedb750022eef7f9d0f833e2bcb661347fa42b9110L100-R101) [[2]](diffhunk://#diff-4726fd086550e3664cc80d29dc96dea24b8568f1d4a700b324f …
> Miscellaneous Improvements from Threshold Consensus Spike

- p2p/src/simulated/network.rs
Removes use of mutexes around the `mailbox` in the implementation of `Peer` by adding one more layer of indirection (when receiving messages from peers) before sending messages to the appropriate channel-specific `mailbox`. We call this an `inbox`, which collates messages from peers. A background task processes the `inbox` and routes the message to the approprate `mailbox`
> [p2p::simulated] Remove locking in `Peer` implementation

- consensus/src/lib.rs
- consensus/src/simplex/mod.rs
- consensus/src/threshold_simplex/mod.rs
> correct comments

- consensus/src/simplex/mocks/application.rs
- consensus/src/simplex/prover.rs
- consensus/src/threshold_simplex/mocks/application.rs
- consensus/src/threshold_simplex/prover.rs
- cryptography/src/lib.rs
- cryptography/src/sha256/mod.rs
- storage/src/mmr/verification.rs
> [cryptography] Add `read_from`

- storage/src/journal/variable.rs
- Make the replay() stream terminate on error to avoid infinite loops if the caller doesn't abort procesing on errors.
- Remove some unnecessary explicit error conversions.
Context: addresses https://github.com/commonwarexyz/monorepo/issues/451
> [commonware-storage/journal/variable] Make the replay() stream terminate on error

- cryptography/src/bls12381/scheme.rs
- cryptography/src/ed25519/scheme.rs
- cryptography/src/secp256r1/scheme.rs
- cryptography/src/sha256/mod.rs
- examples/bridge/src/application/actor.rs
- examples/bridge/src/bin/indexer.rs
- examples/log/src/application/actor.rs
- examples/vrf/src/handlers/arbiter.rs
- examples/vrf/src/handlers/vrf.rs
Related: #464 
Also implement `Debug`.
> [cryptography] Implement `Debug`

- storage/src/mmr/iterator.rs
- storage/src/mmr/mem.rs
Support MMR validity checking so we may recover from partial writes.
> [commonware-storage/mmr] Add MMR validity checker

- .github/workflows/tests.yml
- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
- storage/Cargo.toml
- storage/src/journal/mod.rs
- storage/src/lib.rs
- storage/src/mmr/mod.rs
> [storage] Add WASM Support

- storage/src/journal/fixed.rs
- storage/src/mmr/journaled.rs
- storage/src/mmr/mem.rs
- storage/src/mmr/verification.rs
- Strictly enforce invariant where the newest blob always has room for appending at least one more element.
- Various function doc clarifications.
- Consistently use "prune/pruning" instead of "forget/forgetting"
> [commonware-storage/journal/fixed.rs] stronger invariants, improved language

- .github/workflows/publish.yml
> [CI] Publish `resolver`

- Cargo.lock
- deployer/Cargo.toml
- deployer/src/ec2/aws.rs
- deployer/src/ec2/create.rs
- deployer/src/ec2/destroy.rs
- deployer/src/ec2/mod.rs
- deployer/src/ec2/services.rs
- deployer/src/ec2/update.rs
- deployer/src/ec2/utils.rs
- deployer/src/main.rs
- examples/bridge/src/bin/validator.rs
- examples/chat/src/main.rs
- examples/flood/Cargo.toml
- examples/flood/README.md
- examples/flood/dashboard.json
- examples/flood/src/bin/flood.rs
- examples/flood/src/bin/setup.rs
- examples/log/src/main.rs
- examples/vrf/src/main.rs
- p2p/src/authenticated/config.rs
- stream/src/lib.rs
- stream/src/public_key/handshake.rs
- stream/src/public_key/wire.proto
> [deployer] `update` + System Metrics

- storage/src/archive/mod.rs
- Clarify comment about why the additional checksumming is performed.
- Reformat all header comments to 100 columns.
> [commonware-storage/archive] Clarify purpose of additional checksum

- Cargo.lock
- Cargo.toml
- broadcast/Cargo.toml
- consensus/Cargo.toml
- cryptography/Cargo.toml
- deployer/Cargo.toml
- examples/bridge/Cargo.toml
- examples/chat/Cargo.toml
- examples/flood/Cargo.toml
- examples/log/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- resolver/Cargo.toml
- runtime/Cargo.toml
- storage/Cargo.toml
- stream/Cargo.toml
- utils/Cargo.toml
> [release] 3-9-25

- storage/src/mmr/mem.rs
This allows the MMR implementation to be used for tasks that would otherwise require a mutable merkle tree.
> [commonware-storage/mem/mmr] add ability to update leaves in the in-mem MMR

- deployer/src/ec2/create.rs
- deployer/src/ec2/services.rs
Related: https://github.com/commonwarexyz/alto/issues/26
> [deployer] Rotate Logs + Retain for `4h`

- deployer/src/ec2/aws.rs
- deployer/src/ec2/mod.rs
- deployer/src/ec2/refresh.rs
- deployer/src/ec2/utils.rs
- deployer/src/lib.rs
- deployer/src/main.rs
> [deployer] Add `ec2 refresh` command

- p2p/src/authenticated/actors/spawner/actor.rs
- p2p/src/authenticated/actors/tracker/actor.rs
> [p2p] Improve connected peers metric

- storage/src/mmr/bitmap.rs
- storage/src/mmr/iterator.rs
- storage/src/mmr/mod.rs
First part of an authenticatable bitmap implementation.
Part 2 will include proof generation & verification.
> [commonware-storage/mmr] Authenticatable Bitmap - Part 1

- storage/src/mmr/iterator.rs
- storage/src/mmr/mem.rs
This function will make it convenient to generate a range proof for all MMR updates from a given point in history to tip, since range proof generation requires the exact position of the last leaf in the range.
This PR also changes leaf_pos_to_num to return None instead of panic if the given position is not a leaf, to make it usable in verifying untrusted proofs that provide the leaf positions.
> [commonware-storage/mmr/mem] add ability to get last leaf position

- consensus/src/ordered_broadcast/config.rs
- consensus/src/ordered_broadcast/engine.rs
- consensus/src/ordered_broadcast/mod.rs
> [consensus::ordered_broadcast] remove config.verify_concurrent

- Cargo.lock
- utils/Cargo.toml
- utils/src/lib.rs
Fixes #608 
Tests already exist
> [utils] use codec instead of prost

- storage/src/mmr/journaled.rs
The journaled MMR always caches its size, so we can use the cached value in a non-async size() implementation instead of relying on the async storage trait version.
> [commonware-storage/journaled] add a non-async size method

- storage/src/mmr/mutable.rs
- storage/src/mmr/operation.rs
This makes the mutable MMR inactivity floor easily persistable & provable.
> [commonware-storage/mmr/operaetion] add operation that represents raising of the inactive operations floor

- storage/src/mmr/mem.rs
Update pop() to be able to pop the very oldest retained leaf. This should have been updated in [this PR](https://github.com/commonwarexyz/monorepo/pull/643) but was missed.
> [commonware-storage/mmr/mem] allow popping even the oldest retained leaf

- deployer/src/ec2/aws.rs
- deployer/src/ec2/create.rs
- deployer/src/ec2/mod.rs
- deployer/src/ec2/services.rs
- deployer/src/ec2/update.rs
- deployer/src/ec2/utils.rs
- examples/flood/dashboard.json
> [deployer] Memory profiles

- storage/src/mmr/bitmap.rs
Salvaged these changes from this recently closed PR: https://github.com/commonwarexyz/monorepo/pull/620
> [commonware-storage/mmr/bitmap] minor interface tweaks to authenticatable bitmap

- cryptography/Cargo.toml
- cryptography/src/bls12381/benches/dkg_recovery.rs
- cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
- cryptography/src/bls12381/benches/threshold_signature_recover.rs
> [cryptography] Add bigger benchmarks

- cryptography/src/bls12381/benches/dkg_recovery.rs
- cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
- cryptography/src/bls12381/benches/threshold_signature_recover.rs
Restore 2000 once https://github.com/commonwarexyz/monorepo/pull/720 is merged.
> [ci] Limit to 1000

- storage/src/mmr/mem.rs
Missed this one in https://github.com/commonwarexyz/monorepo/pull/750
> [commonware-storage/mmr] change one more element type from digest to slice

- storage/src/mmr/bitmap.rs
- Consistently use u64 for bit offsets, and usize for byte/chunk offsets.
- Introduce CHUNK_SIZE_BITS (a u64 since it's bits not bytes) for improved code clarity
- Introduce new chunk_pos helper.
> [commonware-storage/bitmap] minor authenticated bitmap cleanup

- Cargo.lock
- p2p/Cargo.toml
- p2p/src/authenticated/actors/tracker/actor.rs
- p2p/src/authenticated/actors/tracker/set.rs
- p2p/src/authenticated/types.rs
- utils/src/bitvec.rs
- utils/src/lib.rs
> [utils] Add `BitVec` type

- consensus/src/simplex/actors/voter/actor.rs
- consensus/src/simplex/mod.rs
- consensus/src/simplex/verifier.rs
- consensus/src/threshold_simplex/actors/voter/actor.rs
- consensus/src/threshold_simplex/mod.rs
- cryptography/src/bls12381/benches/dkg_recovery.rs
- cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
- cryptography/src/bls12381/benches/threshold_signature_recover.rs
- cryptography/src/bls12381/dkg/arbiter.rs
- cryptography/src/bls12381/dkg/dealer.rs
- cryptography/src/bls12381/dkg/mod.rs
- cryptography/src/bls12381/dkg/player.rs
- cryptography/src/bls12381/primitives/ops.rs
- examples/bridge/src/bin/dealer.rs
- examples/bridge/src/bin/validator.rs
- examples/vrf/src/handlers/contributor.rs
- examples/vrf/src/main.rs
- utils/src/lib.rs
> [utils] Remove `Option` from `quorum/max_faults` return type

- consensus/src/threshold_simplex/mocks/supervisor.rs
- cryptography/src/bls12381/primitives/group.rs
- cryptography/src/bls12381/primitives/ops.rs
- cryptography/src/bls12381/primitives/poly.rs
- cryptography/src/bls12381/scheme.rs
- examples/bridge/src/application/supervisor.rs
- examples/bridge/src/bin/dealer.rs
- examples/bridge/src/bin/indexer.rs
- examples/bridge/src/bin/validator.rs
- examples/vrf/src/handlers/vrf.rs
> [cryptography] Remove old serialization functions

- Cargo.lock
- consensus/src/ordered_broadcast/ack_manager.rs
- consensus/src/ordered_broadcast/tip_manager.rs
- consensus/src/simplex/mocks/application.rs
- consensus/src/threshold_simplex/mocks/application.rs
- cryptography/src/bls12381/primitives/group.rs
- cryptography/src/bls12381/scheme.rs
- cryptography/src/ed25519/scheme.rs
- cryptography/src/lib.rs
- cryptography/src/secp256r1/scheme.rs
- cryptography/src/sha256/mod.rs
- examples/flood/Cargo.toml
- examples/flood/src/bin/flood.rs
- examples/vrf/src/handlers/wire.rs
- p2p/src/simulated/network.rs
- resolver/src/p2p/mocks/key.rs
- storage/src/adb/any.rs
- storage/src/adb/operation.rs
- storage/src/archive/mod.rs
- storage/src/bmt/mod.rs
- storage/src/journal/fixed.rs
- storage/src/metadata/storage.rs
- storage/src/mmr/bitmap.rs
- storage/src/mmr/journaled.rs
- storage/src/mmr/verification.rs
- utils/src/array/fixed_bytes.rs
- utils/src/array/mod.rs
- utils/src/array/prefixed_u64.rs
- utils/src/array/u64.rs
> [Array] Remove unnecessary traits

- .github/actions/setup/action.yml
- p2p/src/authenticated/config.rs
- p2p/src/authenticated/mod.rs
- p2p/src/authenticated/network.rs
- p2p/src/authenticated/types.rs
> Remove leftover mentions of protoc/protobuf

- consensus/src/ordered_broadcast/engine.rs
- consensus/src/ordered_broadcast/mocks/reporter.rs
- consensus/src/ordered_broadcast/mocks/validators.rs
- consensus/src/ordered_broadcast/mod.rs
- consensus/src/ordered_broadcast/types.rs
> [consensus/ordered-broadcast] Add External Sequencer Test + Improve Coverage on Sequencer Checks + Emit `Tip` Even if `Sequencer`

- broadcast/src/buffered/config.rs
- broadcast/src/buffered/engine.rs
- broadcast/src/buffered/ingress.rs
- broadcast/src/buffered/metrics.rs
- broadcast/src/buffered/mod.rs
- cryptography/src/bls12381/scheme.rs
- storage/src/archive/mod.rs
> [broadcast/buffered] Expand API

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/src/utils.rs
> [runtime] Introduce Runtime-Agnostic, Asynchronous `RwLock`

- Cargo.lock
- Cargo.toml
- broadcast/Cargo.toml
- codec/Cargo.toml
- consensus/Cargo.toml
- cryptography/Cargo.toml
- deployer/Cargo.toml
- examples/bridge/Cargo.toml
- examples/chat/Cargo.toml
- examples/flood/Cargo.toml
- examples/log/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- resolver/Cargo.toml
- runtime/Cargo.toml
- storage/Cargo.toml
- stream/Cargo.toml
- utils/Cargo.toml
```
Cargo.lock                                         |  34 +-
Cargo.toml                                         |  24 +-
broadcast/Cargo.toml                               |   2 +-
codec/Cargo.toml                                   |   2 +-
codec/src/error.rs                                 |   8 +-
codec/src/lib.rs                                   |   7 +-
codec/src/types/bytes.rs                           |  28 +-
codec/src/types/map.rs                             |  26 +-
codec/src/types/net.rs                             |  12 +-
codec/src/types/primitives.rs                      |  86 +++-
codec/src/types/vec.rs                             |  22 +-
codec/src/varint.rs                                | 506 ++++++++++++++++-----
consensus/Cargo.toml                               | …
```
> [release] v0.0.47

- Cargo.lock
- Cargo.toml
- broadcast/Cargo.toml
- codec/Cargo.toml
- consensus/Cargo.toml
- cryptography/Cargo.toml
- deployer/Cargo.toml
- examples/bridge/Cargo.toml
- examples/chat/Cargo.toml
- examples/flood/Cargo.toml
- examples/log/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- resolver/Cargo.toml
- runtime/Cargo.toml
- storage/Cargo.toml
- stream/Cargo.toml
- utils/Cargo.toml
```
Cargo.lock                              |  34 ++---
Cargo.toml                              |  24 ++--
broadcast/Cargo.toml                    |   2 +-
codec/Cargo.toml                        |   2 +-
consensus/Cargo.toml                    |   2 +-
cryptography/Cargo.toml                 |   2 +-
deployer/Cargo.toml                     |   2 +-
deployer/src/ec2/aws.rs                 |   4 +-
examples/bridge/Cargo.toml              |   2 +-
examples/chat/Cargo.toml                |   2 +-
examples/flood/Cargo.toml               |   2 +-
examples/flood/Dockerfile               |   3 +-
examples/log/Cargo.toml                 |   2 +-
examples/vrf/Cargo.toml                 |   2 +-
macros/Cargo.toml                       |   2 +-
p2p/Cargo.toml                          |   2 +- …
```
> [release] v0.0.48

- storage/src/mmr/mem.rs
Fixes issue where update_leaf is failing with ElementPruned error when updating certain retained nodes.
> [commonware-storage/mmr] allow mem-mmr to access pinned nodes when updating leafs

- examples/flood/src/bin/flood.rs
- runtime/src/lib.rs
- runtime/src/tokio/telemetry.rs
> [runtime] Expand `Logger` Functionality

- Cargo.lock
- Cargo.toml
- broadcast/Cargo.toml
- codec/Cargo.toml
- consensus/Cargo.toml
- cryptography/Cargo.toml
- deployer/Cargo.toml
- examples/bridge/Cargo.toml
- examples/chat/Cargo.toml
- examples/flood/Cargo.toml
- examples/log/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- resolver/Cargo.toml
- runtime/Cargo.toml
- storage/Cargo.toml
- stream/Cargo.toml
- utils/Cargo.toml
```
Cargo.lock                                         |  34 +-
Cargo.toml                                         |  24 +-
broadcast/Cargo.toml                               |   2 +-
broadcast/src/buffered/config.rs                   |   5 +-
broadcast/src/buffered/engine.rs                   | 229 ++++++--
broadcast/src/buffered/ingress.rs                  | 103 ++--
broadcast/src/buffered/mocks.rs                    |  48 +-
broadcast/src/buffered/mod.rs                      | 389 +++++++++++--
broadcast/src/lib.rs                               |  14 +-
codec/Cargo.toml                                   |   2 +-
codec/src/codec.rs                                 |  58 +-
codec/src/config.rs                                | 241 ++++++++
codec/src/error.rs …
```
> [release] v0.0.49

- storage/src/adb/any.rs
- storage/src/archive/storage.rs
- storage/src/index/mod.rs
- storage/src/index/storage.rs
> [storage/index] Add More Test Coverage + Fix `None` Panic with Full State Machine Refactor

- storage/src/adb/operation.rs
Accidentally left some unneeded code that does an extra copy in https://github.com/commonwarexyz/monorepo/pull/889
We no longer move `data` into the returned `Self` so we don't need to copy it out of `buf`.
> [storage] remove unneeded copy in Operation::read_cfg

- cryptography/src/bls12381/primitives/ops.rs
> [cryptography/bls12381] Verify Partial Signatures or Return Any Invalid

- consensus/src/threshold_simplex/actors/mod.rs
- consensus/src/threshold_simplex/actors/resolver/actor.rs
- consensus/src/threshold_simplex/actors/verifier/actor.rs
- consensus/src/threshold_simplex/actors/verifier/ingress.rs
- consensus/src/threshold_simplex/actors/verifier/mod.rs
- consensus/src/threshold_simplex/actors/voter/actor.rs
- consensus/src/threshold_simplex/actors/voter/ingress.rs
- consensus/src/threshold_simplex/actors/voter/mod.rs
- consensus/src/threshold_simplex/engine.rs
- consensus/src/threshold_simplex/mod.rs
- consensus/src/threshold_simplex/types.rs
On a network of 10 validators, this is an ~85% reduction in signature verifications per view.
> [consensus/threshold-simplex] Prefer Efficiency Over Observability

- consensus/src/threshold_simplex/actors/resolver/actor.rs
- consensus/src/threshold_simplex/actors/resolver/mod.rs
- consensus/src/threshold_simplex/actors/verifier/actor.rs
- consensus/src/threshold_simplex/actors/verifier/mod.rs
- consensus/src/threshold_simplex/actors/voter/actor.rs
- consensus/src/threshold_simplex/actors/voter/mod.rs
- consensus/src/threshold_simplex/config.rs
- consensus/src/threshold_simplex/engine.rs
- consensus/src/threshold_simplex/mocks/impersonator.rs
- consensus/src/threshold_simplex/mocks/invalid.rs
- consensus/src/threshold_simplex/mocks/mod.rs
- consensus/src/threshold_simplex/mocks/supervisor.rs
- consensus/src/threshold_simplex/mod.rs
- examples/bridge/src/bin/validator.rs
- p2p/src/simulated/ingress.rs
- p2p/src/simulated/network.rs
> [consensus/threshold-simplex] Integrate `Blocker`

- .github/workflows/benchmark.yml
> [storage] fix benchmark by passing feature properly

- runtime/src/iouring/mod.rs
Helpful reference: https://unixism.net/loti/ref-iouring/io_uring_enter.html
> [runtime] Add optional timeout for iouring operations

- consensus/src/lib.rs
- consensus/src/threshold_simplex/actors/batcher/actor.rs
- consensus/src/threshold_simplex/actors/resolver/actor.rs
- consensus/src/threshold_simplex/actors/voter/actor.rs
- consensus/src/threshold_simplex/engine.rs
- consensus/src/threshold_simplex/mocks/supervisor.rs
- consensus/src/threshold_simplex/types.rs
- cryptography/src/bls12381/benches/bench.rs
- cryptography/src/bls12381/benches/evaluate_point.rs
- cryptography/src/bls12381/benches/partial_verify_multiple_public_keys.rs
- cryptography/src/bls12381/benches/partial_verify_multiple_public_keys_precomputed.rs
- cryptography/src/bls12381/dkg/ops.rs
- cryptography/src/bls12381/primitives/ops.rs
- examples/bridge/src/application/supervisor.rs
- runtime/src/telemetry/metrics/histogram.rs
Future Work: https://github.com/commonwarexyz/monorepo/issues/977
> [commonware/threshold-simplex] `alto` Testing

- Cargo.lock
- Cargo.toml
- broadcast/Cargo.toml
- codec/Cargo.toml
- consensus/Cargo.toml
- consensus/src/ordered_broadcast/types.rs
- consensus/src/simplex/types.rs
- consensus/src/threshold_simplex/types.rs
- cryptography/Cargo.toml
- deployer/Cargo.toml
- examples/bridge/Cargo.toml
- examples/chat/Cargo.toml
- examples/flood/Cargo.toml
- examples/log/Cargo.toml
- examples/vrf/Cargo.toml
- macros/Cargo.toml
- p2p/Cargo.toml
- resolver/Cargo.toml
- runtime/Cargo.toml
- storage/Cargo.toml
- stream/Cargo.toml
- utils/Cargo.toml
Make signing helpers public (for easier testing in external repositories).
> [release] v0.0.52

- consensus/src/simplex/actors/voter/actor.rs
- consensus/src/simplex/actors/voter/mod.rs
- consensus/src/threshold_simplex/actors/batcher/actor.rs
- consensus/src/threshold_simplex/actors/voter/actor.rs
- consensus/src/threshold_simplex/actors/voter/mod.rs
- consensus/src/threshold_simplex/engine.rs
- consensus/src/threshold_simplex/metrics.rs
- consensus/src/threshold_simplex/mod.rs
> [consensus] Fix Pruning Logic

- storage/src/mmr/bitmap.rs
- storage/src/mmr/hasher.rs
- storage/src/mmr/iterator.rs
- storage/src/mmr/journaled.rs
- storage/src/mmr/mem.rs
- storage/src/mmr/mod.rs
- storage/src/mmr/storage.rs
- storage/src/mmr/verification.rs
Adds a Storage implementation over grafted trees to support proof generation & verification over them.
> [storage/mmr] Storage trait implementation for grafted trees

- codec/src/types/map.rs
- codec/src/types/mod.rs
- codec/src/types/set.rs
> [Codec] Add `BTreeMap`, `BTreeSet`, `HashSet`

- storage/src/mmr/bitmap.rs
There was no bug here, but the way the code was documented & structured made me think the unwraps() after pop() on the proof digests might panic. This PR clarifies the handling of final-digest handling and adds a test case to confirm it's working as intended.
> [storage/mmr/bitmap] clarify handling of final digest in bit authentication

- runtime/src/iouring/mod.rs
- runtime/src/network/iouring.rs
- runtime/src/storage/iouring.rs
- runtime/src/tokio/runtime.rs
> [runtime]  add io_uring metrics; make test less flaky

- runtime/src/iouring/mod.rs
Future Work: https://github.com/commonwarexyz/monorepo/issues/1037
> [runtime] change single_issuer config default to false

- stream/src/lib.rs
- stream/src/public_key/connection.rs
- stream/src/public_key/handshake.rs
> [stream] Prevent self-connection

- p2p/src/authenticated/metrics.rs
Replaces an `i32` field with an enum
> [p2p] add MessageType type

- p2p/src/authenticated/actors/listener.rs
- p2p/src/authenticated/actors/peer/actor.rs
- p2p/src/authenticated/actors/tracker/directory.rs
A few nits around using `let Type(foo) = bar` instead of an empty match arm/`.is_none()`
> [p2p] use destructuring syntax

- storage/src/journal/benches/fixed_replay.rs
- storage/src/journal/fixed.rs
Addresses https://github.com/commonwarexyz/monorepo/issues/478 for the `fixed` journal only.
> [storage/journal/fixed] Add ability to start from specific position during replay

- stream/src/public_key/connection.rs
- stream/src/public_key/nonce.rs
Doesn't affect `p2p` since the connection will be terminated anyway, but may technically be considered a bugfix
> [stream] Increment nonce on receive even if decoding fails

- utils/src/lib.rs
https://github.com/commonwarexyz/monorepo/pull/1120#issuecomment-2985163767
> [utils] Fix modulo overflow for 8-byte values of `n`

- storage/src/index/mod.rs
- storage/src/index/storage.rs
> [storage/index] Fix Middle Mutate Case

- pipeline/minimmit.md
> [pipeline/minimmit] Fix typos/misprints

- storage/src/metadata/mod.rs
- storage/src/metadata/storage.rs
Related: https://github.com/commonwarexyz/monorepo/pull/1175
> [storage/metadata] Address Feedback

- storage/fuzz/fuzz_targets/journal_operations.rs
This PR fixes https://github.com/commonwarexyz/monorepo/issues/1201#event-18441673652
> Add start_pos in the fuzz test

- .github/workflows/slow.yml
- Cargo.lock
- Cargo.toml
- stream/Cargo.toml
- stream/fuzz/Cargo.toml
- stream/fuzz/fuzz_targets/confirmation.rs
- stream/fuzz/fuzz_targets/connection.rs
- stream/fuzz/fuzz_targets/e2e.rs
- stream/fuzz/fuzz_targets/handshake.rs
- stream/fuzz/fuzz_targets/lazy_transport.rs
- stream/fuzz/fuzz_targets/stream_state_machine.rs
- stream/fuzz/fuzz_targets/transport.rs
This PR fixes https://github.com/commonwarexyz/monorepo/issues/1187 and also:
- adds a fuzz target for confirmations
- makes minor code-style updates
> [stream] Fix Fuzz Memory Leak

- storage/fuzz/fuzz_targets/journal_operations.rs
This PR fixes the journal operations fuzz target.
> [storage/fuzz] Fix journal operations fuzz test

- cryptography/src/bloomfilter.rs
- cryptography/src/lib.rs
- utils/src/lib.rs
Bloom Filter using the Kirsch-Mitzenmacher Optimization: https://www.eecs.harvard.edu/~michaelm/postscripts/tr-02-05.pdf
> [cryptography] Introduce `BloomFilter`

- storage/fuzz/fuzz_targets/adb_operations.rs
- storage/fuzz/fuzz_targets/archive_operations.rs
- storage/fuzz/fuzz_targets/index_operations.rs
- storage/src/adb/any/mod.rs
- storage/src/adb/any/sync/client.rs
- storage/src/adb/any/sync/mod.rs
- storage/src/adb/any/sync/resolver.rs
- storage/src/adb/benches/any_init.rs
- storage/src/adb/current.rs
- storage/src/archive/benches/utils.rs
- storage/src/archive/mod.rs
- storage/src/index/benches/insert.rs
- storage/src/index/mod.rs
- storage/src/index/storage.rs
- storage/src/lib.rs
- storage/src/translator.rs
> [storage] Move `Translator`

- storage/src/metadata/mod.rs
- storage/src/metadata/storage.rs
> [storage/metadata] Add iterator

- storage/Cargo.toml
- storage/src/freezer/benches/bench.rs
- storage/src/freezer/benches/get.rs
- storage/src/freezer/benches/put.rs
- storage/src/freezer/benches/restart.rs
- storage/src/freezer/benches/utils.rs
- storage/src/freezer/mod.rs
- storage/src/freezer/storage.rs
- storage/src/lib.rs
- storage/src/ordinal/benches/get.rs
- storage/src/ordinal/benches/put.rs
- storage/src/ordinal/benches/restart.rs
Future Work: #1227 
~Future Work: #1243~
Related: #1204 
_Run the command: `cargo bench --bench freezer --quiet 2>/dev/null | grep -E "(^freezer::|time:)"`_
```txt
freezer::get/pattern=random mode=serial reads=1000
time:   [56.686 ms 56.887 ms 57.189 ms]
freezer::get/pattern=random mode=serial reads=10000
time:   [563.62 ms 566.18 ms 568.73 ms]
freezer::get/pattern=random mode=serial reads=50000
time:   [2.8280 s 2.8452 s 2.8691 s]
freezer::get/pattern=random mode=concurrent reads=1000
time:   [18.841 ms 19.428 ms 21.203 ms]
freezer::get/pattern=random mode=concurrent reads=10000
time:   [193.92 ms 198.10 ms 202.34 ms]
freezer::get/pattern=random mode=concurrent reads=50000
time:   [1.0167 s 1.0446 s 1.0665 s]
freezer::get/pattern=recent mode=serial reads=1000
time:   [22.569 ms 22.754 ms …
```
> [storage/freezer] Introduce `freezer`

- consensus/src/ordered_broadcast/engine.rs
- runtime/src/tokio/telemetry.rs
Resolves: #1095 
Resolves: #1255
> [consensus/ordered-broadcast] Reduce Verbosity

- storage/src/archive/mod.rs
- storage/src/archive/prunable/mod.rs
- storage/src/metadata/storage.rs
Related: https://github.com/commonwarexyz/alto/pull/127
> [nits] Final Release Tweaks

- cryptography/src/bls12381/primitives/ops.rs
> [cryptography/bls12381] Use Rayon for Concurrent Recovery

- storage/src/freezer/mod.rs
- storage/src/freezer/storage.rs
> [storage/freezer] Improve Resize Mechanism

- storage/src/index/mod.rs
- storage/src/index/storage.rs
Fixes: #1203 
TL;DR fuzzing ftw
> [storage/index] Implement Custom `Drop`

- .github/workflows/benchmark.yml
> [CI] Add `coding` to benchmarks

- .github/workflows/coverage.yml
- .github/workflows/slow.yml
- Cargo.lock
- Cargo.toml
- coding/fuzz/Cargo.toml
- coding/fuzz/fuzz_targets/reed_solomon.rs
- cryptography/fuzz/Cargo.toml
- cryptography/fuzz/fuzz_targets/blake3_hasher.rs
- cryptography/fuzz/fuzz_targets/bls12381_aggregate_operations.rs
- cryptography/fuzz/fuzz_targets/bls12381_primitive_operations.rs
- cryptography/fuzz/fuzz_targets/bls12381_primitive_threshold_operations.rs
- cryptography/fuzz/fuzz_targets/bls12381_threshold_operations.rs
- cryptography/fuzz/fuzz_targets/common/mod.rs
- cryptography/src/bls12381/primitives/group.rs
This PR adds fuzz tests for the following crates:
-  `bls12381` aggregate and threshold operations
- `blake3`
- `coding`
> Add more fuzz tests: coding, blake3, threshold

- storage/fuzz/fuzz_targets/journal_operations.rs
This PR fixes choosing of `oldest_retained_pos `
> Fix journal fuzz operation

- storage/fuzz/fuzz_targets/bmt_operations.rs
- storage/src/bmt/mod.rs
> [storage/bmt] Follow-Ups

- examples/sync/src/lib.rs
- storage/src/adb/any/mod.rs
- storage/src/adb/any/sync/client.rs
- storage/src/adb/any/sync/resolver.rs
- storage/src/adb/append.rs
- storage/src/adb/current.rs
- storage/src/adb/immutable.rs
- storage/src/adb/mod.rs
- storage/src/adb/operation.rs
- storage/src/journal/variable.rs
- utils/src/array/mod.rs
- utils/src/array/u32.rs
Addresses https://github.com/commonwarexyz/monorepo/issues/1294
> [storage/adb] Introduce `adb::immutable`

- storage/fuzz/Cargo.toml
- storage/fuzz/fuzz_targets/adb_sync.rs
Adds an initial and incomplete harness for adb_sync which we can iterate on going forwards
> Initial adb_sync fuzz test

- cryptography/fuzz/Cargo.toml
- cryptography/fuzz/fuzz_targets/bls12381_tle.rs
- cryptography/fuzz/fuzz_targets/common/mod.rs
This PR initiates fuzzing for timelock encryption.
> Init timelock encryption fuzzing

- cryptography/fuzz/Cargo.toml
- cryptography/fuzz/fuzz_targets/metamorph_lthash.rs
This PR adds a metamorphic fuzzer for lthash.
> Add metamorphic fuzzer for lthash

- runtime/src/utils/buffer/mod.rs
- runtime/src/utils/buffer/read.rs
- Do not leave the buffer in a state where self.buffer().len < self.buffer_size, which can lead to panics if the reader is rewinded. (Addresses https://github.com/commonwarexyz/monorepo/issues/1348)
- Regression test for above issue.
- Document panic condition in read_exact.
> [runtime/utils/buffer] fix out of range bug due to shortened read buffer

- storage/Cargo.toml
- storage/src/adb/any/mod.rs
- storage/src/adb/operation.rs
- storage/src/lib.rs
- storage/src/store/benches/bench.rs
- storage/src/store/benches/restart.rs
- storage/src/store/benches/store_init.rs
- storage/src/store/mod.rs
- storage/src/store/operation.rs
Introduces a new `store` module that contains a simple, unauthenticated `Store` K/V DB.
closes https://github.com/commonwarexyz/monorepo/issues/1206
> [storage] Introduce `store`

- codec/src/varint.rs
- collector/src/p2p/mocks/types.rs
- consensus/src/simplex/mocks/application.rs
- consensus/src/threshold_simplex/mocks/application.rs
- resolver/src/p2p/wire.rs
- storage/src/adb/operation.rs
- storage/src/archive/immutable/storage.rs
WIP: I have two more sections in `storage` I have to fix
Fixes #1363
> Remove usage of `buf.get_u*`

- runtime/src/lib.rs
> [runtime] Fix `Signal` Test Flake

- consensus/src/marshal/actor.rs
- consensus/src/marshal/mod.rs
- utils/src/futures.rs
> [consensus::marshal] Fix: Responses from `broadcast::buffered` are not immediately processed

- runtime/src/utils/buffer/tip.rs
addresses https://github.com/commonwarexyz/monorepo/issues/1349
> [runtime/utils/buffer] use checked add in offset assertion checks

- consensus/src/aggregation/config.rs
- consensus/src/aggregation/engine.rs
- consensus/src/aggregation/mocks/application.rs
- consensus/src/aggregation/mocks/mod.rs
- consensus/src/aggregation/mocks/reporter.rs
- consensus/src/aggregation/mod.rs
- consensus/src/aggregation/types.rs
- consensus/src/threshold_simplex/actors/voter/actor.rs
Related: #1417 
Related: #573 (proper fix)
> [consensus/{threshold_simplex, aggregation}] Replay Activity

- examples/sync/src/databases/immutable.rs
- storage/src/adb/any/fixed/mod.rs
- storage/src/adb/any/variable/mod.rs
- storage/src/adb/benches/variable_init.rs
- storage/src/adb/immutable/mod.rs
- storage/src/adb/immutable/sync/mod.rs
- storage/src/adb/keyless.rs
- storage/src/store/benches/restart.rs
- storage/src/store/mod.rs
- storage/src/store/operation.rs
resolves https://github.com/commonwarexyz/monorepo/issues/1447
> [storage] support associating metadata w/ variable-store commit ops

- p2p/src/utils/mux.rs
Remove per-message lock acquisition and map modification.
> [p2p] Mux Nits

- runtime/src/iouring/mod.rs
Timeout operations were not acounted for when submitting to the ring, this could lead to capacity overflow. Contains a regression test to showcase the problem (panics before the last commit).
> [runtime/iouring] account for linked timeout op space in the SQ

- cryptography/src/bls12381/dkg/mod.rs
This documents the non-uniform output, and why this is acceptable.
Closes #1068
> [cryptography] document non-uniform JF DKG

- Cargo.lock
- Cargo.toml
- cryptography/Cargo.toml
- cryptography/src/lib.rs
- cryptography/src/transcript.rs
c.f. https://github.com/commonwarexyz/monorepo/issues/1483
> Transcript API

- storage/src/mmr/journaled.rs
Fixes assertion failure that can result if one tries to prune an MMR to a position prior to the current pruning boundary, and add regression tests.  This should be a no-op, not a failure.
Resolves https://github.com/commonwarexyz/monorepo/issues/1599
> [storage/mmr/journaled] fix assertion failure when trying to prune to a location earlier than current boundary

- .github/workflows/quint.yml
> Update quint version to 0.28.0

- coding/src/reed_solomon/mod.rs
- consensus/src/threshold_simplex/mocks/supervisor.rs
- cryptography/src/secp256r1/scheme.rs
- examples/estimator/src/lib.rs
- storage/src/bmt/mod.rs
- utils/src/lib.rs
Suppresses some lints added with the new version of clippy.
> [workspace] Fix lints with new clippy version

- .github/workflows/coverage.yml
- .github/workflows/fast.yml
- .github/workflows/quint.yml
- .github/workflows/slow.yml
Adds support for the `merge_group` trigger in all `pull_request`-triggered workflows.
> [ci] Support `merge_group` dispatch trigger

- consensus/src/marshal/actor.rs
- consensus/src/marshal/ingress/mailbox.rs
- consensus/src/marshal/mod.rs
- storage/src/archive/benches/utils.rs
- storage/src/archive/immutable/storage.rs
- storage/src/archive/mod.rs
- storage/src/archive/prunable/storage.rs
- storage/src/ordinal/storage.rs
- storage/src/rmap/mod.rs
> [consensus::marshal] Add getters

- storage/src/adb/verify.rs
- storage/src/mmr/iterator.rs
Resolves https://github.com/commonwarexyz/monorepo/issues/1710
> [storage/mmr] document overflow conditions and provide better panic messages

- macros/tests/select.rs
> [macros] Fix flaky test

- storage/src/mmr/iterator.rs
If the function is passed an overflowing value, it no longer has the log(n) bound on iterations, and can hang for a very long time.
> [storage/mmr] fix potential hang in to_nearest_size by panicking on overflow

- p2p/src/authenticated/lookup/actors/listener.rs
- p2p/src/authenticated/lookup/actors/tracker/actor.rs
- p2p/src/authenticated/lookup/actors/tracker/directory.rs
- p2p/src/authenticated/lookup/actors/tracker/ingress.rs
- p2p/src/authenticated/lookup/actors/tracker/mod.rs
- p2p/src/authenticated/lookup/mod.rs
- p2p/src/authenticated/lookup/network.rs
Resolves: #1605
Previous: #1738
> [p2p/lookup] Filter Unauthenticated IPs

- storage/fuzz/fuzz_targets/adb_any_variable_sync.rs
- storage/fuzz/fuzz_targets/mmr_journaled.rs
- storage/fuzz/fuzz_targets/translator_operations.rs
- Translator test
- Historical proof test
> Fix flaky fuzz tests

- Cargo.lock
- macros/Cargo.toml
- macros/tests/select.rs
> [macros] Cleanup `select!` test

- cryptography/src/bls12381/dkg/mod.rs
> [bls12381/dkg] Improve `test_invalid_commitment_degree`
